/* =========================================================
   questions.js — 題庫（與遊戲邏輯完全分開）
   ---------------------------------------------------------
   欄位說明：
     id              題目編號，格式 [M|U]-[S1..S5|PT]-序號
     level           middle（中年級）／upper（高年級）
     stage           1~5，後測題填 "postTest"
     mode            這題可出現在哪些模式：adventure / quick / challenge / postTest
     skillType       辨認／分類／應用／推理
     radical         這題主要考的部件（結果頁的「常錯部件」用它統計）
     difficulty      基礎／標準／挑戰
     question        題目文字。句子填空用「＿＿」當空格。
     options         選項陣列（順序會在遊戲中隨機打亂）
     answerIndex     正確答案在 options 中的索引
     explanation     解析，一定要指出線索在哪個部件
     correctFeedback 答對回饋
     wrongHint       答錯提示
     focus           （選填）要放進田字格顯示的字或部件。不填就不顯示。
     charOptions     （選填）true 表示選項是單字，畫面會放大成楷體
   ---------------------------------------------------------
   ※ 部件釋義以教育部《重編國語辭典修訂本》的常見用法為準，
     並一律使用「多半」「常和……有關」等保守說法。
   ※ 新增題目：直接在陣列尾端加物件即可，不必改 script.js。
   ========================================================= */

const QUESTION_BANK = [

/* ========================================================
   中年級 · 第 1 關 部件認親（16 題）辨認 8 / 分類 8
   ======================================================== */
{ id:"M-S1-001", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"木", difficulty:"基礎",
  focus:"木",
  question:"看到「木」這個部件，最常和哪一類意思有關？",
  options:["樹木或木頭做的東西","金錢和買賣","心裡的感覺","說話的聲音"], answerIndex:0,
  explanation:"「木」多半出現在和樹木、木材有關的字裡，例如「林」「板」「枝」。",
  correctFeedback:"線索抓到了！看到「木」，先往樹木、木頭的方向想。",
  wrongHint:"想想看「樹」「林」「枝」這幾個字，它們共同的部件是什麼？" },

{ id:"M-S1-002", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"土", difficulty:"基礎",
  focus:"土",
  question:"看到「土」這個部件，最常和哪一類意思有關？",
  options:["泥土、土地或地面","水和液體","布料和衣服","時間早晚"], answerIndex:0,
  explanation:"「土」常出現在和土地、地面有關的字裡，例如「地」「城」「塊」。",
  correctFeedback:"沒錯，「土」把你帶到地面上了。",
  wrongHint:"「地」「城」「塵」都有這個部件，它們都踩在什麼上面？" },

{ id:"M-S1-003", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"言", difficulty:"基礎",
  focus:"言",
  question:"看到「言」這個部件，最常和哪一類意思有關？",
  options:["說話或語言","走路和移動","眼睛看東西","火和熱"], answerIndex:0,
  explanation:"「言」多半和說話、語言有關，例如「說」「話」「語」「請」。",
  correctFeedback:"對！「言」一出現，多半有人在說話。",
  wrongHint:"「說」「話」「語」都有它，這些字都在做同一件事。" },

{ id:"M-S1-004", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"日", difficulty:"基礎",
  focus:"日",
  question:"看到「日」這個部件，最常和哪一類意思有關？",
  options:["太陽、光線或時間","心裡的想法","金屬和工具","竹子做的東西"], answerIndex:0,
  explanation:"「日」本來就是太陽的樣子，常和陽光、天氣、時間有關，例如「晴」「早」「晚」。",
  correctFeedback:"太陽出來了！「日」常指光線或時間。",
  wrongHint:"「晴」「早」「昨」都有它。這些字和一天當中的什麼有關？" },

{ id:"M-S1-005", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"火", difficulty:"基礎",
  focus:"火",
  question:"看到「火」這個部件，最常和哪一類意思有關？",
  options:["火、熱或燃燒","雨水和天氣","腳的動作","房屋和家"], answerIndex:0,
  explanation:"「火」常和燃燒、加熱有關，例如「燒」「烤」「炒」。",
  correctFeedback:"熱起來了！看到「火」先想燃燒或加熱。",
  wrongHint:"「燒」「烤」「炒」都需要什麼？" },

{ id:"M-S1-006", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"忄", difficulty:"基礎",
  focus:"忄",
  question:"看到「忄」這個部件，最常和哪一類意思有關？",
  options:["心情或想法","水和液體","金錢買賣","房屋空間"], answerIndex:0,
  explanation:"「忄」叫豎心旁，是「心」變來的，常出現在和情緒、想法有關的字，例如「快」「怕」「情」。",
  correctFeedback:"你看見心了！「忄」常常提醒我們：這個字和感覺有關。",
  wrongHint:"「怕」「快」「情」都有它，這三個字說的是身體還是感覺？" },

{ id:"M-S1-007", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"食", difficulty:"基礎",
  focus:"食",
  question:"看到「食」（飠）這個部件，最常和哪一類意思有關？",
  options:["食物或吃東西","說話語言","雨和雲","布和線"], answerIndex:0,
  explanation:"「食」多半和吃、食物有關，例如「飯」「餅」「飽」「餓」。",
  correctFeedback:"肚子餓了嗎？「食」常指食物或吃。",
  wrongHint:"「飯」「飽」「餓」都在講同一件事，是哪一件？" },

{ id:"M-S1-008", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"月", difficulty:"挑戰",
  focus:"月",
  question:"「月」這個部件比較特別，下列說法哪一個最恰當？",
  options:["常和月亮或時間有關，但有些字裡的「月」其實是從「肉」變來的","一定都和月亮有關","一定都和肉有關","和水有關"], answerIndex:0,
  explanation:"「明」「朗」的「月」和月光有關；「肚」「腦」「胖」的「月」則是「肉」變形而來。偵探要小心這個陷阱。",
  correctFeedback:"很細心！這正是「月」最容易被誤判的地方。",
  wrongHint:"想想「肚子」的「肚」，它和月亮有關嗎？" },

{ id:"M-S1-009", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"氵", difficulty:"基礎",
  focus:"氵", charOptions:true,
  question:"下列哪一個字裡有「氵」這個部件？",
  options:["池","地","他","也"], answerIndex:0,
  explanation:"「池」的左邊是三點水「氵」，所以和水有關。其他三個字的左邊都不是三點水。",
  correctFeedback:"找到了！三點水常常躲在字的左邊。",
  wrongHint:"這四個字讀音很像，但只有一個字的左邊有三個點。" },

{ id:"M-S1-010", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"扌", difficulty:"標準",
  focus:"扌", charOptions:true,
  question:"下列哪一個字裡有「扌」（手）這個部件？",
  options:["打","叮","盯","釘"], answerIndex:0,
  explanation:"「打」的左邊是提手旁「扌」，和手的動作有關。「叮」是口、「盯」是目、「釘」是金。",
  correctFeedback:"很厲害，這四個字讀音接近，你靠部件分出來了。",
  wrongHint:"這四個字右邊都是「丁」。差別全在左邊，哪一個左邊像一隻手？" },

{ id:"M-S1-011", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"目", difficulty:"標準",
  focus:"目", charOptions:true,
  question:"下列哪一個字裡有「目」這個部件？",
  options:["眨","朋","吹","跳"], answerIndex:0,
  explanation:"「眨」的左邊是「目」，和眼睛有關。「朋」是月、「吹」是口、「跳」是足。",
  correctFeedback:"眼睛找到眼睛了。",
  wrongHint:"「眨眼」的「眨」在做什麼動作？用身體哪個部位？" },

{ id:"M-S1-012", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"足", difficulty:"標準",
  focus:"足", charOptions:true,
  question:"下列哪一個字裡有「足」這個部件？",
  options:["跳","桃","逃","挑"], answerIndex:0,
  explanation:"四個字右邊都是「兆」，但「跳」的左邊是「足」，所以和腳的動作有關。",
  correctFeedback:"漂亮！同樣讀音，部件不同，意思就不同。",
  wrongHint:"跳起來要用身體哪一個部位？找出左邊是那個部位的字。" },

{ id:"M-S1-013", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"貝", difficulty:"標準",
  focus:"貝", charOptions:true,
  question:"下列哪一個字裡有「貝」這個部件？",
  options:["財","材","村","時"], answerIndex:0,
  explanation:"「財」的左邊是「貝」。古代用貝殼當錢，所以「貝」常和金錢、財物有關。「材」「村」是木。",
  correctFeedback:"認出來了！「貝」是錢的線索。",
  wrongHint:"「財」和「材」讀音一樣，但一個和錢有關、一個和木頭有關。" },

{ id:"M-S1-014", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"竹", difficulty:"標準",
  focus:"竹", charOptions:true,
  question:"下列哪一個字上面有「竹」（𥫗）這個部件？",
  options:["筆","書","畫","字"], answerIndex:0,
  explanation:"「筆」的上面是竹字頭。古代的筆桿用竹子做的，所以帶竹字頭。",
  correctFeedback:"對，竹字頭常戴在字的頭上。",
  wrongHint:"四個字都和寫字有關，但只有一個字頂上有兩撇竹葉。" },

{ id:"M-S1-015", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"亻", difficulty:"基礎",
  focus:"亻", charOptions:true,
  question:"下列哪一個字裡有「亻」（人）這個部件？",
  options:["們","朋","明","吃"], answerIndex:0,
  explanation:"「們」的左邊是單人旁「亻」，和人有關。",
  correctFeedback:"找到人了！單人旁常站在字的左邊。",
  wrongHint:"「我們」「你們」的「們」，說的是人還是月亮？" },

{ id:"M-S1-016", level:"middle", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"口", difficulty:"基礎",
  focus:"口", charOptions:true,
  question:"下列哪一個字裡有「口」這個部件？",
  options:["吹","林","河","跑"], answerIndex:0,
  explanation:"「吹」的左邊是「口」，要用嘴巴才能吹。",
  correctFeedback:"沒錯，吹氣要用嘴。",
  wrongHint:"吹蠟燭的時候，你用的是身體哪一個部位？" },

/* ========================================================
   中年級 · 第 2 關 字義偵探（16 題）全為分類
   ======================================================== */
{ id:"M-S2-001", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"氵", difficulty:"基礎",
  question:"「河、洗、淋」這幾個字，大多和什麼意思有關？",
  options:["水或液體","心裡的想法","金錢財物","房屋空間"], answerIndex:0,
  explanation:"這三個字都有「氵」。三點水常提示這個字和水、液體、流動有關。",
  correctFeedback:"你從一群字裡歸納出線索了，這就是偵探的功夫。",
  wrongHint:"先把三個字共同的部件圈出來，再想它像什麼。" },

{ id:"M-S2-002", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"忄", difficulty:"基礎",
  question:"「想、念、忘」這幾個字，大多和什麼意思有關？",
  options:["心裡的想法或記憶","腳的動作","天氣變化","器具工具"], answerIndex:0,
  explanation:"這三個字下面都有「心」。心常和思考、情感、記憶有關。",
  correctFeedback:"對，這三個字都發生在心裡。",
  wrongHint:"把三個字的下半部遮起來看看，它們共用了哪個部件？" },

{ id:"M-S2-003", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"言", difficulty:"基礎",
  question:"「說、話、語」這幾個字，大多和什麼意思有關？",
  options:["說話或語言","眼睛看東西","走路移動","泥土地面"], answerIndex:0,
  explanation:"這三個字都有「言」，多半和開口說話有關。",
  correctFeedback:"聽見了嗎？「言」在說話。",
  wrongHint:"它們左邊那個部件，本來畫的就是嘴巴上方發出的聲音。" },

{ id:"M-S2-004", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"貝", difficulty:"標準",
  question:"「財、買、貴」這幾個字，大多和什麼意思有關？",
  options:["金錢、財物或價值","風雨天氣","竹子做的東西","說話語氣"], answerIndex:0,
  explanation:"這三個字都有「貝」。古人曾以貝殼作為錢幣，所以「貝」常和錢財、價值有關。",
  correctFeedback:"你找到古代的錢了。",
  wrongHint:"想想看，古代還沒有硬幣的時候，人們拿什麼東西當錢？" },

{ id:"M-S2-005", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"木", difficulty:"基礎",
  question:"「樹、林、枝」這幾個字，大多和什麼意思有關？",
  options:["樹木","火和熱","水和河流","人的動作"], answerIndex:0,
  explanation:"這三個字都有「木」，所以多半和樹木有關。",
  correctFeedback:"一棵、兩棵，森林出現了。",
  wrongHint:"這三個字如果放在一起，你會看到什麼景色？" },

{ id:"M-S2-006", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"扌", difficulty:"基礎",
  question:"「打、抱、推」這幾個字，大多和什麼意思有關？",
  options:["用手做的動作","用腳做的動作","用眼睛看","用嘴巴說"], answerIndex:0,
  explanation:"這三個字左邊都是提手旁「扌」，多半和手的動作有關。",
  correctFeedback:"對，這些動作都要伸出手。",
  wrongHint:"你打人、抱人、推人的時候，用的是哪個部位？" },

{ id:"M-S2-007", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"日", difficulty:"標準",
  question:"「晴、昨、晚」這幾個字，大多和什麼意思有關？",
  options:["天氣或時間","說話語言","金屬工具","水和液體"], answerIndex:0,
  explanation:"這三個字都有「日」。太陽和白天、天氣、時間都有關係。",
  correctFeedback:"太陽走了一圈，時間就過去了。",
  wrongHint:"「昨天」「晚上」「晴天」都在講什麼？" },

{ id:"M-S2-008", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"火", difficulty:"標準",
  question:"「燒、烤、煙」這幾個字，大多和什麼意思有關？",
  options:["火或燃燒","水和洗滌","布料衣服","房屋建築"], answerIndex:0,
  explanation:"這三個字都有「火」（「烤」的下面是四點火「灬」，也是火）。",
  correctFeedback:"注意到「灬」也是火，觀察得很仔細。",
  wrongHint:"烤肉的時候，底下需要什麼？" },

{ id:"M-S2-009", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"目", difficulty:"標準",
  question:"「眼、睛、眨」這幾個字，大多和什麼意思有關？",
  options:["眼睛或看的動作","嘴巴或說話","耳朵或聽","鼻子或呼吸"], answerIndex:0,
  explanation:"這三個字都有「目」，多半和眼睛有關。",
  correctFeedback:"眼睛的家找到了。",
  wrongHint:"「目」這個字本來就是畫一隻眼睛的樣子。" },

{ id:"M-S2-010", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"足", difficulty:"標準",
  question:"「跑、跳、踢」這幾個字，大多和什麼意思有關？",
  options:["腳的動作","手的動作","說話的動作","看的動作"], answerIndex:0,
  explanation:"這三個字左邊都是「足」，多半和腳的動作有關。",
  correctFeedback:"跑跳踢，都是腳的工作。",
  wrongHint:"上體育課的時候，這三件事你用哪裡做？" },

{ id:"M-S2-011", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"土", difficulty:"標準",
  question:"「地、城、塊」這幾個字，大多和什麼意思有關？",
  options:["土地或地面","天空和雲","水和海","火和光"], answerIndex:0,
  explanation:"這三個字都有「土」，常和土地、地面、土做成的東西有關。",
  correctFeedback:"腳踏實地，答對了。",
  wrongHint:"這三個字共同的部件，是我們每天踩在腳下的東西。" },

{ id:"M-S2-012", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"竹", difficulty:"標準",
  question:"「筆、筷、籃」這幾個字，大多和什麼意思有關？",
  options:["用竹子做的東西","用金屬做的東西","用布做的東西","用泥土做的東西"], answerIndex:0,
  explanation:"這三個字上面都是竹字頭。古代這些器物常用竹子製作，所以帶竹字頭。",
  correctFeedback:"你看出材料了，這一步很關鍵。",
  wrongHint:"這三個字的上面，看起來像兩片什麼葉子？" },

{ id:"M-S2-013", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"食", difficulty:"基礎",
  question:"「飯、餅、飽」這幾個字，大多和什麼意思有關？",
  options:["食物或吃","衣服或穿","房子或住","車子或走"], answerIndex:0,
  explanation:"這三個字左邊都是「飠」（食），多半和食物、吃有關。",
  correctFeedback:"吃飽了才有力氣辦案。",
  wrongHint:"這三個字放在一起，你會想到餐桌還是衣櫃？" },

{ id:"M-S2-014", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"女", difficulty:"標準",
  question:"「姊、妹、媽」這幾個字，大多和什麼意思有關？",
  options:["女性或家人稱呼","動物名稱","天氣現象","工具器物"], answerIndex:0,
  explanation:"這三個字左邊都是「女」，常和女性或親屬稱呼有關。",
  correctFeedback:"這是一家人的線索。",
  wrongHint:"這三個人在家裡，通常是誰？" },

{ id:"M-S2-015", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"雨", difficulty:"標準",
  question:"「雲、雪、露」這幾個字，大多和什麼意思有關？",
  options:["天空的水氣或天氣現象","地上的石頭","身體的部位","說話的方式"], answerIndex:0,
  explanation:"這三個字上面都是「雨」，多半和天上落下或凝結的水氣有關。",
  correctFeedback:"抬頭看天空，答案就在那裡。",
  wrongHint:"這三樣東西，你要往上看還是往下看才找得到？" },

{ id:"M-S2-016", level:"middle", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"辶", difficulty:"挑戰",
  question:"「追、送、迎」這幾個字，大多和什麼意思有關？",
  options:["走路、移動或路程","坐著不動","說話聊天","吃東西"], answerIndex:0,
  explanation:"這三個字都有「辶」（走之旁），常和行走、移動有關。",
  correctFeedback:"「辶」像一條路，字就在路上走。",
  wrongHint:"追人、送人、迎接人，這三件事需不需要移動位置？" },
];

/* ========================================================
   中年級 · 第 3 關 錯字修復（18 題）全為應用
   ======================================================== */
QUESTION_BANK.push(
{ id:"M-S3-001", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"日", difficulty:"基礎", charOptions:true,
  question:"今天太陽很大，天氣很＿＿朗。",
  options:["晴","情","清","請"], answerIndex:0,
  explanation:"天氣和陽光有關，要用有「日」的「晴」。「情」是心、「清」是水、「請」是言。",
  correctFeedback:"你用「日」找到太陽了。",
  wrongHint:"天氣好不好，跟太陽有關。四個字裡哪一個藏著太陽？" },

{ id:"M-S3-002", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"忄", difficulty:"基礎", charOptions:true,
  question:"他今天心＿＿很好，一直笑。",
  options:["情","晴","清","請"], answerIndex:0,
  explanation:"心裡的感覺要用有「忄」的「情」。豎心旁提示這個字和心情有關。",
  correctFeedback:"心情的線索，就在豎心旁。",
  wrongHint:"「心＿」在講感覺。哪一個字的左邊像一顆心？" },

{ id:"M-S3-003", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"氵", difficulty:"基礎", charOptions:true,
  question:"這杯水很＿＿澈，可以看見杯底。",
  options:["清","晴","情","請"], answerIndex:0,
  explanation:"和水有關，要用有「氵」的「清」。三點水提示這個字和水有關。",
  correctFeedback:"三點水出現，水就變乾淨了。",
  wrongHint:"句子在講「水」。哪一個字左邊有三個點？" },

{ id:"M-S3-004", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"有問題的時候，要舉手＿＿問老師。",
  options:["請","清","晴","情"], answerIndex:0,
  explanation:"要開口說話，所以用有「言」的「請」。",
  correctFeedback:"開口之前，先找到「言」。",
  wrongHint:"問老師的時候，你要用嘴巴還是用水？" },

{ id:"M-S3-005", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"目", difficulty:"標準", charOptions:true,
  question:"他的眼＿＿又大又亮。",
  options:["睛","晴","精","情"], answerIndex:0,
  explanation:"眼睛是身體器官，要用有「目」的「睛」。「晴」是日、「精」是米、「情」是心。",
  correctFeedback:"「目」就是眼睛，這條線索最直接。",
  wrongHint:"這四個字讀音都很像。句子在講眼睛，哪一個字左邊也是眼睛？" },

{ id:"M-S3-006", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"米", difficulty:"挑戰", charOptions:true,
  question:"睡飽之後，他一整天都很有＿＿神。",
  options:["精","睛","晴","情"], answerIndex:0,
  explanation:"「精」的左邊是「米」，本來和挑選過的細米有關，後來引申為「精細、精力」。這裡先記住：講眼睛用「睛」，講精力用「精」。",
  correctFeedback:"很細！「睛」和「精」差一個部件，意思就分開了。",
  wrongHint:"「有＿神」講的不是眼球，而是力氣和狀態。" },

{ id:"M-S3-007", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"扌", difficulty:"基礎", charOptions:true,
  question:"表演結束，大家用力＿＿手。",
  options:["拍","怕","泊","伯"], answerIndex:0,
  explanation:"拍手要用手，所以用有「扌」的「拍」。",
  correctFeedback:"提手旁一出現，動作就交給手了。",
  wrongHint:"拍手用的是身體哪個部位？找出左邊像手的字。" },

{ id:"M-S3-008", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"忄", difficulty:"基礎", charOptions:true,
  question:"打雷的時候，弟弟很害＿＿。",
  options:["怕","拍","泊","伯"], answerIndex:0,
  explanation:"害怕是一種感覺，用有「忄」的「怕」。",
  correctFeedback:"感覺的事，找豎心旁準沒錯。",
  wrongHint:"害怕發生在手上還是心裡？" },

{ id:"M-S3-009", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"氵", difficulty:"標準", charOptions:true,
  question:"媽媽用熱水＿＿了一壺茶。",
  options:["泡","抱","跑","包"], answerIndex:0,
  explanation:"泡茶要用水，所以用有「氵」的「泡」。「抱」是手、「跑」是足。",
  correctFeedback:"熱水一沖，三點水就對了。",
  wrongHint:"泡茶少不了什麼？把有那樣東西的部件找出來。" },

{ id:"M-S3-010", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"足", difficulty:"標準", charOptions:true,
  question:"上課鐘響了，他趕快＿＿進教室。",
  options:["跑","泡","抱","包"], answerIndex:0,
  explanation:"跑步用腳，所以用有「足」的「跑」。",
  correctFeedback:"用腳的動作，帶「足」。",
  wrongHint:"從走廊衝進教室，用的是腳還是手？" },

{ id:"M-S3-011", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"扌", difficulty:"標準", charOptions:true,
  question:"姊姊輕輕＿＿著剛出生的妹妹。",
  options:["抱","跑","泡","包"], answerIndex:0,
  explanation:"抱人要用手，所以用有「扌」的「抱」。「包」沒有提手旁，是包起來的意思。",
  correctFeedback:"手一伸出來，「扌」就出現了。",
  wrongHint:"抱妹妹的時候，你的手在做什麼？" },

{ id:"M-S3-012", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"氵", difficulty:"基礎", charOptions:true,
  question:"村子旁邊有一條清澈的小＿＿。",
  options:["河","何","荷","可"], answerIndex:0,
  explanation:"小河是水，用有「氵」的「河」。「荷」是艹，指荷花。",
  correctFeedback:"水的線索又被你抓到了。",
  wrongHint:"小河裡流的是什麼？" },

{ id:"M-S3-013", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"上課的時候不要一直講＿＿。",
  options:["話","活","畫","化"], answerIndex:0,
  explanation:"講話是說話，用有「言」的「話」。「活」是水、「畫」和圖有關。",
  correctFeedback:"要說話，先找「言」。",
  wrongHint:"「講＿」是在做什麼？用嘴巴的字左邊會有什麼？" },

{ id:"M-S3-014", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"金", difficulty:"標準", charOptions:true,
  question:"他把零＿＿存進撲滿裡。",
  options:["錢","淺","線","賤"], answerIndex:0,
  explanation:"錢幣多半是金屬做的，所以「錢」帶「金」。「淺」是水、「線」是糸（絲線）。",
  correctFeedback:"金字旁提示我們：這是金屬做的東西。",
  wrongHint:"撲滿裡裝的東西，是用什麼材料做的？" },

{ id:"M-S3-015", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"糸", difficulty:"標準", charOptions:true,
  question:"奶奶用毛＿＿織了一件外套。",
  options:["線","錢","淺","賤"], answerIndex:0,
  explanation:"「線」的左邊是「糸」，和絲、線、布料有關。",
  correctFeedback:"「糸」就是一束絲，織東西當然找它。",
  wrongHint:"織外套要用線，線是金屬做的還是絲做的？" },

{ id:"M-S3-016", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"言", difficulty:"基礎", charOptions:true,
  question:"第一節是國語＿＿。",
  options:["課","棵","顆","果"], answerIndex:0,
  explanation:"上課會聽老師講解，「課」帶「言」。「棵」是木、「顆」是頁。",
  correctFeedback:"三個字讀音一樣，你靠部件分出來了。",
  wrongHint:"「國語＿」是在教室裡做什麼？跟說話有沒有關係？" },

{ id:"M-S3-017", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"木", difficulty:"標準", charOptions:true,
  question:"操場旁邊種了一＿＿大榕樹。",
  options:["棵","課","顆","果"], answerIndex:0,
  explanation:"數樹木用「棵」，左邊是「木」。",
  correctFeedback:"樹的量詞，帶著木。",
  wrongHint:"要數的東西是樹。哪一個字左邊是樹？" },

{ id:"M-S3-018", level:"middle", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"頁", difficulty:"挑戰", charOptions:true,
  question:"天上有一＿＿好亮的星星。",
  options:["顆","棵","課","果"], answerIndex:0,
  explanation:"數圓圓小小的東西用「顆」，右邊是「頁」。「頁」本來和頭有關，圓形的東西也常用它。",
  correctFeedback:"很好，「棵」數樹、「顆」數圓的東西。",
  wrongHint:"星星是一根一根的樹，還是一顆一顆圓圓的？" }
);

/* ========================================================
   中年級 · 第 4 關 陌生字推理（18 題）全為推理
   ======================================================== */
QUESTION_BANK.push(
{ id:"M-S4-001", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"氵", difficulty:"基礎", focus:"潤",
  question:"看到「潤」這個字，先猜它可能和什麼有關？",
  options:["水分、濕潤","金錢買賣","走路移動","說話聲音"], answerIndex:0,
  explanation:"「潤」的左邊是「氵」，所以先往水的方向猜。它的意思正是有水分、不乾燥。",
  correctFeedback:"就算沒學過這個字，部件也把方向指出來了。",
  wrongHint:"別急著猜讀音。先看左邊那三個點像什麼。" },

{ id:"M-S4-002", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"貝", difficulty:"標準", focus:"販",
  question:"看到「販」這個字，先猜它可能和什麼有關？",
  options:["買賣或財物","樹木植物","天氣變化","身體動作"], answerIndex:0,
  explanation:"「販」的左邊是「貝」，多半和錢財、買賣有關。「販賣」就是買進賣出。",
  correctFeedback:"看到「貝」，就想到錢。",
  wrongHint:"左邊那個部件，古代人拿它當錢用。" },

{ id:"M-S4-003", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"辶", difficulty:"標準", focus:"遞",
  question:"看到「遞」這個字，先猜它可能和什麼有關？",
  options:["移動、傳送或路途","吃東西","下雨","看東西"], answerIndex:0,
  explanation:"「遞」有「辶」（走之旁），常和移動、傳送有關。「傳遞」就是把東西送過去。",
  correctFeedback:"「辶」像一條路，東西正在路上被送出去。",
  wrongHint:"這個字下面那條彎彎的線，像不像一條路？" },

{ id:"M-S4-004", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"火", difficulty:"標準", focus:"焰",
  question:"看到「焰」這個字，先猜它可能和什麼有關？",
  options:["火或燃燒","水或海","布或衣服","石頭或山"], answerIndex:0,
  explanation:"「焰」的左邊是「火」，所以和火有關。「火焰」就是燃燒時的火光。",
  correctFeedback:"火苗的線索，一眼就看出來。",
  wrongHint:"左邊那個部件，晚上會發光發熱。" },

{ id:"M-S4-005", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"忄", difficulty:"基礎", focus:"悅",
  question:"看到「悅」這個字，先猜它可能和什麼有關？",
  options:["心情或感覺","金屬工具","雨水天氣","竹製器物"], answerIndex:0,
  explanation:"「悅」的左邊是「忄」，多半和心情有關。「喜悅」就是高興。",
  correctFeedback:"豎心旁一出現，就往感覺想。",
  wrongHint:"左邊那個部件，是「心」變瘦以後的樣子。" },

{ id:"M-S4-006", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"言", difficulty:"標準", focus:"詠",
  question:"看到「詠」這個字，先猜它可能和什麼有關？",
  options:["用聲音吟唱或說出來","用手拿東西","用腳走路","用眼睛看"], answerIndex:0,
  explanation:"「詠」的左邊是「言」，和發出聲音、說唱有關。「吟詠」就是有聲調地誦讀。",
  correctFeedback:"聲音的線索，藏在「言」裡。",
  wrongHint:"左邊那個部件，通常代表嘴巴在做事。" },

{ id:"M-S4-007", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"金", difficulty:"挑戰", focus:"鑄",
  question:"看到「鑄」這個字，先猜它可能和什麼有關？",
  options:["金屬的製作","水的流動","說話的方式","心裡的想法"], answerIndex:0,
  explanation:"「鑄」的左邊是「金」，多半和金屬有關。「鑄劍」就是把金屬熔化後做成器物。",
  correctFeedback:"金字旁就是金屬的招牌。",
  wrongHint:"這個字左邊，和「錢」「銀」「鐵」共用同一個部件。" },

{ id:"M-S4-008", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"目", difficulty:"標準", focus:"眺",
  question:"看到「眺」這個字，先猜它可能和什麼有關？",
  options:["用眼睛看","用腳跳","用手挑","用嘴吃"], answerIndex:0,
  explanation:"「眺」的左邊是「目」，和眼睛有關。「眺望」就是往遠處看。",
  correctFeedback:"同樣是「兆」，換了部件就換了意思。",
  wrongHint:"這個字和「跳」「挑」很像，差別只在左邊。左邊是什麼器官？" },

{ id:"M-S4-009", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"足", difficulty:"標準", focus:"踏",
  question:"看到「踏」這個字，先猜它可能和什麼有關？",
  options:["腳的動作","手的動作","說話","下雨"], answerIndex:0,
  explanation:"「踏」的左邊是「足」，和腳有關。「踏步」就是用腳踩。",
  correctFeedback:"腳的動作，帶著「足」。",
  wrongHint:"左邊那個部件，和「跑」「跳」是同一家。" },

{ id:"M-S4-010", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"竹", difficulty:"挑戰", focus:"筏",
  question:"看到「筏」這個字，先猜它可能和什麼有關？",
  options:["用竹子或木頭做的器物","金屬做的刀","布做的衣服","泥土做的牆"], answerIndex:0,
  explanation:"「筏」上面是竹字頭，多半和竹製物有關。「竹筏」是用竹子綁成、可以在水上行走的工具。",
  correctFeedback:"竹字頭常常說明材料。",
  wrongHint:"這個字戴著一頂帽子，那頂帽子是兩片什麼葉？" },

{ id:"M-S4-011", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"食", difficulty:"標準", focus:"饑",
  question:"看到「饑」這個字，先猜它可能和什麼有關？",
  options:["食物或吃不飽","走路","說話","下雨"], answerIndex:0,
  explanation:"「饑」的左邊是「飠」（食），多半和食物有關。「饑餓」就是沒東西吃、肚子空。",
  correctFeedback:"食字旁一出現，就想到吃。",
  wrongHint:"這個字和「飯」「飽」共用左邊的部件。" },

{ id:"M-S4-012", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"土", difficulty:"標準", focus:"塌",
  question:"看到「塌」這個字，先猜它可能和什麼有關？",
  options:["土或建築倒下","水或河流","火或熱","說話"], answerIndex:0,
  explanation:"「塌」的左邊是「土」，多半和土地、建築有關。「倒塌」就是房子或土堆垮下來。",
  correctFeedback:"土的線索被你發現了。",
  wrongHint:"左邊那個部件，和「地」「城」是同一家。" },

{ id:"M-S4-013", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"木", difficulty:"挑戰", focus:"樑",
  question:"看到「樑」這個字，先猜它可能和什麼有關？",
  options:["木頭或木造的建材","金屬工具","食物","心情"], answerIndex:0,
  explanation:"「樑」的左邊是「木」，多半和木材有關。屋頂上橫著撐住房子的木頭就叫「樑」。",
  correctFeedback:"木頭撐起了整間房子。",
  wrongHint:"這個字左邊是一棵樹的樣子。" },

{ id:"M-S4-014", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"女", difficulty:"標準", focus:"姪",
  question:"看到「姪」這個字，先猜它可能和什麼有關？",
  options:["人的親屬關係","動物","天氣","器具"], answerIndex:0,
  explanation:"「姪」的左邊是「女」，這一類字常和人、尤其是親屬稱呼有關。「姪女」是兄弟姊妹的女兒。",
  correctFeedback:"稱呼親人的字，常常帶「女」。",
  wrongHint:"這個字和「姊」「妹」「媽」共用左邊的部件。" },

{ id:"M-S4-015", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"氵", difficulty:"基礎", focus:"沐",
  question:"看到「沐」這個字，先猜它可能和什麼有關？",
  options:["水，例如洗澡","木頭","火","說話"], answerIndex:0,
  explanation:"「沐」左邊是「氵」，右邊是「木」。左邊的部件常常提示意思，所以先猜和水有關。「沐浴」就是洗澡。",
  correctFeedback:"很棒，你沒有被右邊的「木」騙走。",
  wrongHint:"這個字有兩個部件。哪一邊比較常提示意思？" },

{ id:"M-S4-016", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"扌", difficulty:"標準", focus:"拭",
  question:"看到「拭」這個字，先猜它可能和什麼有關？",
  options:["手的動作","腳的動作","眼睛的動作","嘴巴的動作"], answerIndex:0,
  explanation:"「拭」的左邊是「扌」，和手的動作有關。「擦拭」就是用手擦。",
  correctFeedback:"提手旁一出現，動作就交給手。",
  wrongHint:"左邊那個部件，和「打」「抱」「推」是同一家。" },

{ id:"M-S4-017", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"宀", difficulty:"標準", focus:"寓",
  question:"看到「寓」這個字，先猜它可能和什麼有關？",
  options:["房屋或居住","下雨","走路","吃飯"], answerIndex:0,
  explanation:"「寓」上面是「宀」（寶蓋頭），本來畫的是屋頂，常和房屋、居住有關。「公寓」就是住的地方。",
  correctFeedback:"屋頂下面住著人，你看見了。",
  wrongHint:"這個字頭上那一撇一橫，像不像一個屋頂？" },

{ id:"M-S4-018", level:"middle", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"雨", difficulty:"挑戰", focus:"霖",
  question:"看到「霖」這個字，先猜它可能和什麼有關？",
  options:["雨","樹林裡的動物","石頭","布料"], answerIndex:0,
  explanation:"「霖」上面是「雨」，下面是「林」。上面的部件提示意思，所以和雨有關；「甘霖」指久旱之後下的好雨。",
  correctFeedback:"你沒有被下面的「林」帶走，很好。",
  wrongHint:"這個字有「林」也有「雨」。哪一個在上面？上面那個常常負責提示意思。" }
);

/* ========================================================
   中年級 · 第 5 關 終極密碼（12 題）四種能力混合
   ======================================================== */
QUESTION_BANK.push(
{ id:"M-S5-001", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"艹", difficulty:"標準",
  question:"「花、草、菜」這幾個字，大多和什麼意思有關？",
  options:["植物","動物","石頭","金屬"], answerIndex:0,
  explanation:"這三個字上面都是「艹」（草字頭），多半和草本植物有關。",
  correctFeedback:"草字頭一戴上，就是植物家族。",
  wrongHint:"這三個字頭上都有兩根小草。" },

{ id:"M-S5-002", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"穴", difficulty:"標準", charOptions:true,
  question:"下過雨的地上有一個小水＿＿。",
  options:["窪","洼","佳","住"], answerIndex:0,
  explanation:"「窪」和低下積水的地方有關。若不確定，也可以先用部件判斷：帶「氵」「穴」的字比較可能和水或凹陷處有關，「佳」「住」則是人。",
  correctFeedback:"先排除「亻」的字，這一步很正確。",
  wrongHint:"先把左邊是「亻」的字刪掉，它們多半在講人。" },

{ id:"M-S5-003", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"門", difficulty:"標準", focus:"闖",
  question:"看到「闖」這個字，先猜它可能和什麼有關？",
  options:["從門裡衝出去或衝進來","吃東西","下雨","寫字"], answerIndex:0,
  explanation:"「闖」外面是「門」，裡面是「馬」。一匹馬從門裡衝出來，所以有猛然衝過去的意思。",
  correctFeedback:"你把整個畫面讀出來了，這就是部件的力量。",
  wrongHint:"這個字外面圍著什麼？裡面關著什麼動物？" },

{ id:"M-S5-004", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"辨認", radical:"忄", difficulty:"標準", charOptions:true,
  question:"下列哪一個字裡有「忄」這個部件？",
  options:["情","晴","清","請"], answerIndex:0,
  explanation:"「情」的左邊是豎心旁「忄」。其餘三個分別是「日」「氵」「言」。",
  correctFeedback:"四個字讀音一樣，你靠部件分開了它們。",
  wrongHint:"這四個字右邊都是「青」。答案在左邊。" },

{ id:"M-S5-005", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"扌", difficulty:"標準", charOptions:true,
  question:"哥哥在房間裡＿＿書包，準備出門。",
  options:["揹","背","悲","杯"], answerIndex:0,
  explanation:"用手（肩背）把東西扛起來的動作，帶「扌」的「揹」最合適。「悲」是心、「杯」是木。",
  correctFeedback:"動作的字，多半帶提手旁。",
  wrongHint:"這是一個動作。哪一個字的左邊像一隻手？" },

{ id:"M-S5-006", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"石", difficulty:"標準",
  question:"「砂、碎、磚」這幾個字，大多和什麼意思有關？",
  options:["石頭或硬的東西","水或液體","心情","說話"], answerIndex:0,
  explanation:"這三個字都有「石」，多半和石頭、硬的材料有關。",
  correctFeedback:"硬邦邦的線索，你摸到了。",
  wrongHint:"這三個字左邊共用的部件，是路邊常見的東西。" },

{ id:"M-S5-007", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"貝", difficulty:"挑戰", focus:"賒",
  question:"看到「賒」這個字，先猜它可能和什麼有關？",
  options:["買賣或金錢","走路","說話","下雨"], answerIndex:0,
  explanation:"「賒」的左邊是「貝」，多半和錢財有關。「賒帳」就是先拿東西、以後再付錢。",
  correctFeedback:"「貝」永遠是錢的線索。",
  wrongHint:"左邊那個部件，和「財」「買」「貴」是同一家。" },

{ id:"M-S5-008", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"日", difficulty:"挑戰", charOptions:true,
  question:"太陽下山了，天色漸漸變＿＿。",
  options:["暗","按","案","岸"], answerIndex:0,
  explanation:"天色和光線有關，用有「日」的「暗」。「按」是手、「案」是木、「岸」是山。",
  correctFeedback:"光線的事，交給「日」。",
  wrongHint:"天色亮不亮，跟太陽有沒有關係？" },

{ id:"M-S5-009", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"車", difficulty:"標準",
  question:"「輪、軌、輛」這幾個字，大多和什麼意思有關？",
  options:["車子或交通工具","食物","衣服","天氣"], answerIndex:0,
  explanation:"這三個字都有「車」，多半和車輛有關。",
  correctFeedback:"車子開過去了。",
  wrongHint:"火車在什麼上面走？車子有幾個什麼？" },

{ id:"M-S5-010", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"鳥", difficulty:"標準", focus:"鴉",
  question:"看到「鴉」這個字，先猜它可能和什麼有關？",
  options:["一種鳥","一種魚","一種花","一種石頭"], answerIndex:0,
  explanation:"「鴉」的右邊是「鳥」，多半是某一種鳥。「烏鴉」是黑色的鳥。",
  correctFeedback:"鳥字旁，就是鳥的名牌。",
  wrongHint:"這個字右邊那個部件，本來就是畫一隻鳥。" },

{ id:"M-S5-011", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"言", difficulty:"挑戰", charOptions:true,
  question:"這件事情他一直沒有跟我＿＿明白。",
  options:["說","脫","悅","稅"], answerIndex:0,
  explanation:"要開口講清楚，用有「言」的「說」。「脫」是肉月、「悅」是心、「稅」是禾。",
  correctFeedback:"四個字讀音接近，你抓住了「言」。",
  wrongHint:"「＿明白」是用嘴巴做的事。" },

{ id:"M-S5-012", level:"middle", stage:5, mode:["adventure","challenge"], skillType:"辨認", radical:"辶", difficulty:"挑戰", charOptions:true,
  question:"下列哪一個字裡有「辶」這個部件？",
  options:["逃","桃","跳","挑"], answerIndex:0,
  explanation:"四個字右邊都是「兆」。「逃」帶「辶」和移動有關，「桃」是木、「跳」是足、「挑」是手。",
  correctFeedback:"同一個「兆」，四個部件、四種意思，你全分清楚了。",
  wrongHint:"「辶」長得像一條彎彎的路，走在字的左下方。" }
);

/* ========================================================
   中年級 · 後測（15 題）語氣中性、不加故事包裝
   ======================================================== */
QUESTION_BANK.push(
{ id:"M-PT-001", level:"middle", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"氵", difficulty:"基礎",
  question:"「氵」這個部件，最常和哪一類意思有關？",
  options:["水或液體","金錢財物","心情想法","房屋空間"], answerIndex:0,
  explanation:"「氵」（三點水）多半出現在和水、液體、清洗、流動有關的字中。",
  correctFeedback:"正確。",
  wrongHint:"請回想「河」「洗」「淋」的共同部件。" },

{ id:"M-PT-002", level:"middle", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"忄", difficulty:"基礎",
  question:"「忄」這個部件，最常和哪一類意思有關？",
  options:["心情或想法","腳的動作","竹製器物","金屬工具"], answerIndex:0,
  explanation:"「忄」由「心」變來，常和情緒、思考有關。",
  correctFeedback:"正確。",
  wrongHint:"請回想「怕」「快」「情」的共同部件。" },

{ id:"M-PT-003", level:"middle", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"貝", difficulty:"標準",
  question:"「貝」這個部件，最常和哪一類意思有關？",
  options:["金錢、財物或價值","樹木植物","雨水天氣","說話語言"], answerIndex:0,
  explanation:"古代以貝殼為貨幣，因此「貝」常和錢財、價值有關。",
  correctFeedback:"正確。",
  wrongHint:"「財」「買」「貴」都有這個部件。" },

{ id:"M-PT-004", level:"middle", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"扌", difficulty:"標準", charOptions:true,
  question:"下列哪一個字含有「扌」部件？",
  options:["推","堆","誰","雖"], answerIndex:0,
  explanation:"「推」的左邊是提手旁「扌」。「堆」是土、「誰」是言。",
  correctFeedback:"正確。",
  wrongHint:"四個字右邊都有「隹」，請比較左邊。" },

{ id:"M-PT-005", level:"middle", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"目", difficulty:"標準", charOptions:true,
  question:"下列哪一個字含有「目」部件？",
  options:["眠","民","泯","抿"], answerIndex:0,
  explanation:"「眠」的左邊是「目」，和閉眼睡覺有關。",
  correctFeedback:"正確。",
  wrongHint:"「睡眠」和身體哪個器官有關？" },

{ id:"M-PT-006", level:"middle", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"竹", difficulty:"標準",
  question:"「筆、筷、籃」的共同部件提示這些東西的什麼？",
  options:["製作的材料","使用的地點","擁有的人","出現的季節"], answerIndex:0,
  explanation:"竹字頭多半提示這些器物是用竹子製作的。",
  correctFeedback:"正確。",
  wrongHint:"部件有時提示意思，有時提示材料。這三個字屬於哪一種？" },

{ id:"M-PT-007", level:"middle", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"日", difficulty:"基礎", charOptions:true,
  question:"選出正確的字：明天應該是個大＿＿天。",
  options:["晴","情","清","請"], answerIndex:0,
  explanation:"天氣和陽光有關，用帶「日」的「晴」。",
  correctFeedback:"正確。",
  wrongHint:"天氣好壞和太陽有關。" },

{ id:"M-PT-008", level:"middle", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"選出正確的字：他很有禮貌，總是先＿＿問。",
  options:["請","清","晴","情"], answerIndex:0,
  explanation:"開口詢問，用帶「言」的「請」。",
  correctFeedback:"正確。",
  wrongHint:"問人要用嘴巴。" },

{ id:"M-PT-009", level:"middle", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"足", difficulty:"標準", charOptions:true,
  question:"選出正確的字：他一口氣＿＿完一千公尺。",
  options:["跑","泡","抱","包"], answerIndex:0,
  explanation:"用腳的動作，帶「足」的「跑」。",
  correctFeedback:"正確。",
  wrongHint:"跑步用腳。" },

{ id:"M-PT-010", level:"middle", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"木", difficulty:"標準", charOptions:true,
  question:"選出正確的字：門口有兩＿＿榕樹。",
  options:["棵","顆","課","果"], answerIndex:0,
  explanation:"數樹木用「棵」，左邊是「木」。",
  correctFeedback:"正確。",
  wrongHint:"要數的是樹。" },

{ id:"M-PT-011", level:"middle", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"氵", difficulty:"挑戰", charOptions:true,
  question:"選出正確的字：這條河的水很＿＿，可以看見石頭。",
  options:["淺","錢","線","賤"], answerIndex:0,
  explanation:"水深水淺屬於水的狀態，用帶「氵」的「淺」。「錢」帶「金」、「線」帶「糸」。",
  correctFeedback:"正確。",
  wrongHint:"題目在講水，請找左邊有三個點的字。" },

{ id:"M-PT-012", level:"middle", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"氵", difficulty:"基礎", focus:"沖",
  question:"「沖」這個字最可能和什麼有關？",
  options:["水","火","土","金屬"], answerIndex:0,
  explanation:"「沖」的左邊是「氵」，和水的沖刷有關。",
  correctFeedback:"正確。",
  wrongHint:"請看左邊的部件。" },

{ id:"M-PT-013", level:"middle", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"辶", difficulty:"標準", focus:"迅",
  question:"「迅」這個字最可能和什麼有關？",
  options:["移動或速度","食物","衣服","石頭"], answerIndex:0,
  explanation:"「迅」帶「辶」，多半和行走、移動有關，引申為快速。",
  correctFeedback:"正確。",
  wrongHint:"「辶」代表在路上移動。" },

{ id:"M-PT-014", level:"middle", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"火", difficulty:"標準", focus:"炙",
  question:"「炙」這個字最可能和什麼有關？",
  options:["火或烤","水或洗","風或吹","土或埋"], answerIndex:0,
  explanation:"「炙」下面是「火」，上面是「肉」，把肉放在火上，所以和燒烤有關。",
  correctFeedback:"正確。",
  wrongHint:"請看這個字的下半部。" },

{ id:"M-PT-015", level:"middle", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"宀", difficulty:"挑戰", focus:"寢",
  question:"「寢」這個字最可能和什麼有關？",
  options:["房屋或睡覺休息的地方","走路","買賣","天氣"], answerIndex:0,
  explanation:"「寢」上面是「宀」（屋頂），多半和房屋、居住有關。「寢室」就是睡覺的房間。",
  correctFeedback:"正確。",
  wrongHint:"請看這個字最上面那個像屋頂的部件。" }
);

/* ========================================================
   高年級 · 第 1 關 部件認親（20 題）辨認 9 / 分類 11
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-S1-001", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"刂", difficulty:"基礎", focus:"刂",
  question:"「刂」（刀）這個部件，最常和哪一類意思有關？",
  options:["刀、切割或分開","水和液體","說話語言","房屋建築"], answerIndex:0,
  explanation:"「刂」是「刀」放在字右邊的樣子，常和切、割、分有關，例如「割」「剪」「刻」。",
  correctFeedback:"立刀旁站在右邊，帶著刀鋒。",
  wrongHint:"「割」「剪」「刺」共用右邊的部件，那個部件很鋒利。" },

{ id:"U-S1-002", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"攵", difficulty:"標準", focus:"攵",
  question:"「攵」（攴）這個部件，最常和哪一類意思有關？",
  options:["敲打，或使人做某件事的動作","水的流動","植物生長","金屬材料"], answerIndex:0,
  explanation:"「攵」本來像手拿棍子敲打的樣子，常出現在「教」「救」「改」這類表示施加動作的字。",
  correctFeedback:"很好，這個部件常代表「有人動手促使某事發生」。",
  wrongHint:"「教」「改」「敲」共用右邊的部件，它像一隻拿著東西的手。" },

{ id:"U-S1-003", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"灬", difficulty:"標準", focus:"灬",
  question:"「灬」這個部件，最常和哪一類意思有關？",
  options:["火或熱","水滴","眼淚","沙子"], answerIndex:0,
  explanation:"「灬」是「火」放在字底部的樣子，常和加熱、燃燒有關，例如「煮」「熱」「蒸」。不過「魚」「馬」的「灬」則另有來源，要小心。",
  correctFeedback:"四點不是水，是火。這一題很多人會錯。",
  wrongHint:"「煮」「熱」「蒸」都要用到什麼？" },

{ id:"U-S1-004", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"彳", difficulty:"標準", focus:"彳",
  question:"「彳」這個部件，最常和哪一類意思有關？",
  options:["行走或道路","心情感受","飲食","布料"], answerIndex:0,
  explanation:"「彳」由「行」的一半變來，常和走路、路徑有關，例如「往」「徒」「復」。",
  correctFeedback:"雙人旁其實不是人，是一條路。",
  wrongHint:"「往」「徒」「街」都在做同一件事：從一處到另一處。" },

{ id:"U-S1-005", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"糸", difficulty:"基礎", focus:"糸",
  question:"「糸」（糹）這個部件，最常和哪一類意思有關？",
  options:["絲線、繩索或布料","石頭","火焰","米糧"], answerIndex:0,
  explanation:"「糸」本來畫的是一束絲，常和線、繩、織品有關，例如「紅」「絲」「織」「綁」。",
  correctFeedback:"一束絲，牽出整個布料家族。",
  wrongHint:"「線」「織」「綁」都需要什麼細細長長的東西？" },

{ id:"U-S1-006", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"頁", difficulty:"標準", focus:"頁",
  question:"「頁」這個部件，最常和哪一類意思有關？",
  options:["頭部或臉","書本紙張","樹葉","腳掌"], answerIndex:0,
  explanation:"「頁」本來就是畫一個人的頭，常和頭、臉有關，例如「頭」「顏」「頸」「額」。和「一頁書」是後來才有的用法。",
  correctFeedback:"這個部件最容易被書本騙走，你沒被騙。",
  wrongHint:"「頭」「顏」「頸」都在身體的哪一段？" },

{ id:"U-S1-007", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"皿", difficulty:"標準", focus:"皿",
  question:"「皿」這個部件，最常和哪一類意思有關？",
  options:["盛裝東西的器皿","田地","眼睛","門窗"], answerIndex:0,
  explanation:"「皿」本來畫的是一個容器，常和碗、盆、盤這類器皿有關。",
  correctFeedback:"看到「皿」，先想到裝東西的器具。",
  wrongHint:"「盆」「盤」「盛」下面共用的部件，長得像一個有腳的容器。" },

{ id:"U-S1-008", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"疒", difficulty:"標準", focus:"疒",
  question:"「疒」這個部件，最常和哪一類意思有關？",
  options:["疾病或身體不適","房屋","刀劍","車輛"], answerIndex:0,
  explanation:"「疒」本來畫的是人躺在床上的樣子，常和生病有關，例如「病」「痛」「疲」「症」。",
  correctFeedback:"病字頭一出現，多半身體不舒服。",
  wrongHint:"「病」「痛」「疼」共用外框，那個外框像不像一張床？" },

{ id:"U-S1-009", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"隹", difficulty:"挑戰", focus:"隹",
  question:"「隹」這個部件，最常和哪一類意思有關？",
  options:["鳥類","水中的魚","農作物","石器"], answerIndex:0,
  explanation:"「隹」本來畫的是短尾的鳥，常出現在「雀」「雁」「雅」這類和鳥有關的字。不過「誰」「推」的「隹」只表聲音，不表意思。",
  correctFeedback:"很好，你也注意到「隹」不一定都表示意思。",
  wrongHint:"「雀」「雁」都有牠。牠會飛。" },

{ id:"U-S1-010", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"禾", difficulty:"標準", focus:"禾",
  question:"「禾」這個部件，最常和哪一類意思有關？",
  options:["穀物或農作","木頭家具","水流","布匹"], answerIndex:0,
  explanation:"「禾」本來畫的是彎腰結穗的稻子，常和穀類、農事有關，例如「稻」「秋」「稼」。",
  correctFeedback:"稻穗低頭，農田出現了。",
  wrongHint:"「稻」「秋」「種」共用左邊的部件，它長在田裡。" },

{ id:"U-S1-011", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"阝", difficulty:"挑戰", focus:"阝",
  question:"關於「阝」這個部件，下列說法哪一個最恰當？",
  options:["放在字左邊多半和山丘、高低地勢有關；放在右邊多半和城市、地方有關","不管左右都表示耳朵","不管左右都表示城市","不管左右都表示山"], answerIndex:0,
  explanation:"左邊的「阝」由「阜」變來（如「陸」「陡」「陵」），右邊的「阝」由「邑」變來（如「郊」「都」「郡」）。位置不同，來源不同。",
  correctFeedback:"這是高年級最關鍵的分辨之一，你抓到了。",
  wrongHint:"比較「陡」和「郊」，同樣的符號，一個在左邊、一個在右邊。" },

{ id:"U-S1-012", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"貝", difficulty:"標準", focus:"貝", charOptions:true,
  question:"下列哪一個字含有「貝」部件？",
  options:["賠","陪","倍","培"], answerIndex:0,
  explanation:"「賠」的左邊是「貝」，和金錢有關。「陪」是阝、「倍」是亻、「培」是土。",
  correctFeedback:"四個字讀音相同，你用部件切開了它們。",
  wrongHint:"四個字右邊都是「咅」。要賠的是錢，哪一個左邊是錢？" },

{ id:"U-S1-013", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"辶", difficulty:"標準", focus:"辶", charOptions:true,
  question:"下列哪一個字含有「辶」部件？",
  options:["遍","篇","偏","扁"], answerIndex:0,
  explanation:"「遍」帶「辶」，和走遍、到處有關。「篇」是竹、「偏」是亻。",
  correctFeedback:"走之旁把「遍」帶到路上去了。",
  wrongHint:"「走遍全世界」的「遍」，需要移動嗎？" },

{ id:"U-S1-014", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"糸", difficulty:"標準", focus:"糸", charOptions:true,
  question:"下列哪一個字含有「糸」部件？",
  options:["緞","鍛","段","煅"], answerIndex:0,
  explanation:"「緞」左邊是「糸」，是一種絲織品。「鍛」是金，指打鐵。",
  correctFeedback:"布和金屬，就靠部件分開。",
  wrongHint:"「綢緞」是布還是金屬？" },

{ id:"U-S1-015", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"言", difficulty:"標準", focus:"言", charOptions:true,
  question:"下列哪一個字含有「言」部件？",
  options:["諒","涼","掠","晾"], answerIndex:0,
  explanation:"「諒」左邊是「言」，和說出理解、體諒有關。「涼」是水、「掠」是手、「晾」是日。",
  correctFeedback:"體諒是說出來的理解。",
  wrongHint:"四個字右邊都是「京」。答案在左邊。" },

{ id:"U-S1-016", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"皿", difficulty:"挑戰", focus:"皿", charOptions:true,
  question:"下列哪一個字含有「皿」部件？",
  options:["盟","盯","盲","省"], answerIndex:0,
  explanation:"「盟」下面是「皿」。「盯」「盲」「省」下面（或左邊）都是「目」，和眼睛有關。",
  correctFeedback:"「皿」和「目」長得像，你分出來了。",
  wrongHint:"「皿」有四隻腳的感覺，「目」中間有兩橫。仔細看下半部。" },

{ id:"U-S1-017", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"彳", difficulty:"挑戰", focus:"彳", charOptions:true,
  question:"下列哪一個字含有「彳」部件？",
  options:["徒","途","塗","涂"], answerIndex:0,
  explanation:"「徒」左邊是「彳」，「途」帶「辶」。兩者都和走路有關，但部件不同。「塗」是土、「涂」是水。",
  correctFeedback:"兩個都在走路，但只有一個帶「彳」。",
  wrongHint:"「辶」在字的左下角包住右半邊；「彳」則是三筆立在左邊。" },

{ id:"U-S1-018", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"刂", difficulty:"標準", focus:"刂", charOptions:true,
  question:"下列哪一個字含有「刂」部件？",
  options:["剩","乘","勝","盛"], answerIndex:0,
  explanation:"「剩」右邊是「刂」，本義和多出來的部分有關。「勝」是力、「盛」是皿。",
  correctFeedback:"立刀旁站在右邊，很好認。",
  wrongHint:"哪一個字的右邊有兩豎，像一把直立的刀？" },

{ id:"U-S1-019", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"辨認", radical:"忄", difficulty:"標準", focus:"忄", charOptions:true,
  question:"下列哪一個字含有「忄」部件？",
  options:["慣","貫","實","貴"], answerIndex:0,
  explanation:"「慣」左邊是「忄」，和心理習慣有關。「貫」「貴」帶「貝」。",
  correctFeedback:"習慣長在心裡。",
  wrongHint:"「習慣」是身體的動作，還是心裡養成的傾向？" },

{ id:"U-S1-020", level:"upper", stage:1, mode:["adventure","quick","challenge"], skillType:"分類", radical:"弓", difficulty:"標準", focus:"弓",
  question:"「弓」這個部件，最常和哪一類意思有關？",
  options:["弓箭，或拉開、彎曲的動作","眼睛","嘴巴","雨水"], answerIndex:0,
  explanation:"「弓」常和弓箭或拉開的動作有關，例如「張」「引」「弦」。",
  correctFeedback:"弓一拉開，「張」就出現了。",
  wrongHint:"「張開」「引導」的動作，像不像在拉一把弓？" }
);

/* ========================================================
   高年級 · 第 2 關 字義偵探（20 題）全為分類
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-S2-001", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"刂", difficulty:"基礎",
  question:"「割、剪、刺」這幾個字，大多和什麼意思有關？",
  options:["用刀切割或穿刺","用手抓握","用腳踩踏","用嘴說話"], answerIndex:0,
  explanation:"這三個字都有「刂」（立刀旁），多半和刀的動作有關。",
  correctFeedback:"刀鋒的線索被你找到了。",
  wrongHint:"這三個字右邊共用的部件很鋒利。" },

{ id:"U-S2-002", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"攵", difficulty:"標準",
  question:"「教、救、改」這幾個字，大多和什麼意思有關？",
  options:["有人施加動作，使某件事發生","靜止不動","天氣變化","器皿容器"], answerIndex:0,
  explanation:"這三個字都有「攵」，本來像手持棍棒敲打，引申為促使、施行某種動作。",
  correctFeedback:"「攵」代表有人在動手做事。",
  wrongHint:"教人、救人、改變，都需要有人主動出手嗎？" },

{ id:"U-S2-003", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"灬", difficulty:"標準",
  question:"「煮、熱、蒸」這幾個字，大多和什麼意思有關？",
  options:["火或加熱","水滴落下","風的吹動","土的堆積"], answerIndex:0,
  explanation:"這三個字下面都是「灬」，是「火」的變形，所以和加熱有關。",
  correctFeedback:"四點火，不是四滴水。",
  wrongHint:"煮東西、蒸東西，鍋子底下要放什麼？" },

{ id:"U-S2-004", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"彳", difficulty:"標準",
  question:"「往、徒、復」這幾個字，大多和什麼意思有關？",
  options:["行走或路途","飲食","衣物","器皿"], answerIndex:0,
  explanation:"這三個字都有「彳」，由「行」變來，常和走路、路徑有關。",
  correctFeedback:"你認出這條路了。",
  wrongHint:"「往前走」「徒步」「來回往復」，都在做什麼？" },

{ id:"U-S2-005", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"糸", difficulty:"基礎",
  question:"「紅、絲、織」這幾個字，大多和什麼意思有關？",
  options:["絲線或布料","石頭","火焰","穀物"], answerIndex:0,
  explanation:"這三個字都有「糸」，和絲線、紡織有關。連顏色的「紅」也是，因為古代顏色多由染布而來。",
  correctFeedback:"連顏色都和染布有關，觀察得很細。",
  wrongHint:"為什麼「紅」這個顏色字，左邊會是絲？想想染布。" },

{ id:"U-S2-006", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"頁", difficulty:"標準",
  question:"「頭、顏、頸」這幾個字，大多和什麼意思有關？",
  options:["頭部或臉","書本","樹葉","腳"], answerIndex:0,
  explanation:"這三個字都有「頁」，「頁」本來畫的是人的頭部。",
  correctFeedback:"「頁」的真身是一顆頭。",
  wrongHint:"這三個字指的都是身體的同一個區域。" },

{ id:"U-S2-007", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"貝", difficulty:"標準",
  question:"「貴、賠、賺」這幾個字，大多和什麼意思有關？",
  options:["金錢或價值","走路","說話","天氣"], answerIndex:0,
  explanation:"這三個字都有「貝」，古代以貝為錢，因此和金錢、價值有關。",
  correctFeedback:"錢的線索，永遠是「貝」。",
  wrongHint:"這三個字都會出現在買東西的時候。" },

{ id:"U-S2-008", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"言", difficulty:"基礎",
  question:"「誠、訓、誦」這幾個字，大多和什麼意思有關？",
  options:["說話或言語","看東西","走路","吃飯"], answerIndex:0,
  explanation:"這三個字都有「言」，多半和口說、言語有關。",
  correctFeedback:"「言」在說話。",
  wrongHint:"訓話、誦讀，都要開口。" },

{ id:"U-S2-009", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"皿", difficulty:"標準",
  question:"「盆、盤、盛」這幾個字，大多和什麼意思有關？",
  options:["容器或裝東西","眼睛","田地","門窗"], answerIndex:0,
  explanation:"這三個字下面都是「皿」，和盛裝東西的器具有關。",
  correctFeedback:"「皿」是容器的標記。",
  wrongHint:"這三個字下面共用的部件，長得像一個放在桌上的碗。" },

{ id:"U-S2-010", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"阝", difficulty:"挑戰",
  question:"「陸、陡、陵」這幾個字（阝在左邊），大多和什麼意思有關？",
  options:["山丘或高低地勢","城市或地方","耳朵","刀劍"], answerIndex:0,
  explanation:"左邊的「阝」由「阜」變來，本義是土山，所以常和地勢高低有關。",
  correctFeedback:"左阝是山，你分清楚了。",
  wrongHint:"「陡坡」「山陵」都在描寫地面的什麼？" },

{ id:"U-S2-011", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"阝", difficulty:"挑戰",
  question:"「郊、都、郡」這幾個字（阝在右邊），大多和什麼意思有關？",
  options:["城市、地方或行政區","山丘高低","耳朵","車輛"], answerIndex:0,
  explanation:"右邊的「阝」由「邑」變來，「邑」指人聚居的城邑，所以和城市、地方有關。",
  correctFeedback:"右阝是城，這一組最容易混淆。",
  wrongHint:"「郊區」「都市」講的是地形，還是人住的地方？" },

{ id:"U-S2-012", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"弓", difficulty:"標準",
  question:"「張、引、弦」這幾個字，大多和什麼意思有關？",
  options:["弓，或拉開、伸展的動作","水的流動","火的燃燒","土的堆積"], answerIndex:0,
  explanation:"這三個字都有「弓」。拉弓的動作引申出「張開」「引導」等意思。",
  correctFeedback:"弓一拉，字就伸展開了。",
  wrongHint:"這三個字左邊共用的部件，是一種武器。" },

{ id:"U-S2-013", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"隹", difficulty:"標準",
  question:"「雀、雁、雅」這幾個字，大多和什麼意思有關？",
  options:["鳥類","魚類","昆蟲","植物"], answerIndex:0,
  explanation:"這三個字都有「隹」，本義是短尾的鳥。",
  correctFeedback:"一群鳥飛過去了。",
  wrongHint:"麻雀、大雁，這兩種動物有什麼共同點？" },

{ id:"U-S2-014", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"魚", difficulty:"基礎",
  question:"「鮮、鯨、鱗」這幾個字，大多和什麼意思有關？",
  options:["魚或水中的動物","鳥類","家畜","昆蟲"], answerIndex:0,
  explanation:"這三個字都有「魚」，多半和魚或水中生物有關。",
  correctFeedback:"魚的線索很明顯。",
  wrongHint:"這三個字左邊共用的部件，會游泳。" },

{ id:"U-S2-015", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"疒", difficulty:"標準",
  question:"「病、痛、疲」這幾個字，大多和什麼意思有關？",
  options:["疾病或身體不適","房屋建築","刀劍武器","車輛交通"], answerIndex:0,
  explanation:"這三個字都有「疒」，本來像人躺在床上，和生病有關。",
  correctFeedback:"病字頭把三個字都送進了病房。",
  wrongHint:"這三個字的外框，像不像一個人靠著床？" },

{ id:"U-S2-016", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"見", difficulty:"標準",
  question:"「視、覽、觀」這幾個字，大多和什麼意思有關？",
  options:["看","聽","說","走"], answerIndex:0,
  explanation:"這三個字都有「見」，「見」下面是「人」、上面是「目」，本義就是看。",
  correctFeedback:"「見」裡面藏著一隻眼睛。",
  wrongHint:"視力、參觀、瀏覽，都用哪個感官？" },

{ id:"U-S2-017", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"禾", difficulty:"標準",
  question:"「秋、稻、種」這幾個字，大多和什麼意思有關？",
  options:["穀物或農事","樹木家具","石頭礦物","布料衣飾"], answerIndex:0,
  explanation:"這三個字都有「禾」，本義是結穗的稻子，所以和農作有關。連「秋」也是，因為秋天是收穀的季節。",
  correctFeedback:"連季節都和農事有關，讀得很深。",
  wrongHint:"為什麼「秋」左邊是「禾」？秋天在田裡做什麼？" },

{ id:"U-S2-018", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"力", difficulty:"基礎",
  question:"「勞、勤、勉」這幾個字，大多和什麼意思有關？",
  options:["出力或努力","休息","睡覺","吃飯"], answerIndex:0,
  explanation:"這三個字都有「力」，多半和用力、努力有關。",
  correctFeedback:"用力的字，帶著「力」。",
  wrongHint:"勞動、勤勞、勉強，都需要付出什麼？" },

{ id:"U-S2-019", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"鬼", difficulty:"挑戰",
  question:"「魂、魄、魅」這幾個字，大多和什麼意思有關？",
  options:["精神、靈魂或神鬼之事","金屬器物","河流湖泊","農作收成"], answerIndex:0,
  explanation:"這三個字都有「鬼」，古人用來指看不見的精神或靈體。這類字的意思偏抽象，判斷時要保守一些。",
  correctFeedback:"抽象的東西也有部件線索。",
  wrongHint:"「靈魂」「魄力」講的是看得見的東西，還是看不見的？" },

{ id:"U-S2-020", level:"upper", stage:2, mode:["adventure","quick","challenge"], skillType:"分類", radical:"止", difficulty:"挑戰",
  question:"「步、涉、歷」這幾個字裡的「止」，最可能和什麼意思有關？",
  options:["腳或行走","停下不動","嘴巴","眼睛"], answerIndex:0,
  explanation:"「止」本來畫的是一隻腳掌，所以在「步」「涉」「歷」裡多半和行走有關。它後來才有「停止」的意思，這一點容易搞混。",
  correctFeedback:"很細！「止」的本義是腳，不是停止。",
  wrongHint:"「步」是兩隻什麼疊在一起？" }
);

/* ========================================================
   高年級 · 第 3 關 錯字修復（22 題）全為應用
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-S3-001", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"貝", difficulty:"標準", charOptions:true,
  question:"他打破了鄰居的玻璃，只好＿＿錢給人家。",
  options:["賠","陪","倍","培"], answerIndex:0,
  explanation:"賠錢和金錢有關，用帶「貝」的「賠」。「陪」帶右阝、「倍」帶亻、「培」帶土。",
  correctFeedback:"要付錢，就找「貝」。",
  wrongHint:"這四個字讀音相同。句子裡出現「錢」，該找哪個部件？" },

{ id:"U-S3-002", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"阝", difficulty:"標準", charOptions:true,
  question:"媽媽今天特別＿＿我去看牙醫。",
  options:["陪","賠","倍","培"], answerIndex:0,
  explanation:"陪伴是人和人在一起，用帶右「阝」的「陪」。這裡要靠語意判斷：不是付錢（貝），也不是倍數（亻）。",
  correctFeedback:"你用語意排除了「賠」，思路正確。",
  wrongHint:"媽媽是付錢給你，還是跟你一起去？" },

{ id:"U-S3-003", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"扌", difficulty:"標準", charOptions:true,
  question:"警察在路口＿＿下那輛超速的車。",
  options:["攔","欄","瀾","蘭"], answerIndex:0,
  explanation:"攔阻是手的動作，用帶「扌」的「攔」。「欄」是木（欄杆）、「瀾」是水（波瀾）。",
  correctFeedback:"動作的字，看提手旁。",
  wrongHint:"這是一個動作。用手做的動作，左邊會是什麼？" },

{ id:"U-S3-004", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"木", difficulty:"標準", charOptions:true,
  question:"陽台的＿＿杆有點鬆，很危險。",
  options:["欄","攔","瀾","蘭"], answerIndex:0,
  explanation:"欄杆多用木材做成，帶「木」的「欄」最合適。",
  correctFeedback:"材料的線索藏在部件裡。",
  wrongHint:"欄杆是一種動作，還是一個東西？它用什麼材料做？" },

{ id:"U-S3-005", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"火", difficulty:"標準", charOptions:true,
  question:"冬天太＿＿了，皮膚容易乾裂。",
  options:["燥","躁","操","澡"], answerIndex:0,
  explanation:"乾燥缺水和火、熱有關，用帶「火」的「燥」。「躁」帶足（急躁）、「澡」帶水（洗澡）。",
  correctFeedback:"火在旁邊烤，水分就少了。",
  wrongHint:"「乾＿」講的是缺水。哪一個字帶著會把水烤乾的部件？" },

{ id:"U-S3-006", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"足", difficulty:"挑戰", charOptions:true,
  question:"他個性很急，做事常常毛毛躁＿＿的。",
  options:["躁","燥","操","澡"], answerIndex:0,
  explanation:"「躁」帶「足」，本來和腳不安分、走來走去有關，引申為性子急。",
  correctFeedback:"急躁的人，腳停不下來。",
  wrongHint:"一個人急的時候，身體哪個部位最先動起來？" },

{ id:"U-S3-007", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"氵", difficulty:"標準", charOptions:true,
  question:"運動完流了一身汗，趕快去洗＿＿。",
  options:["澡","躁","燥","操"], answerIndex:0,
  explanation:"洗澡要用水，用帶「氵」的「澡」。",
  correctFeedback:"三點水，一身輕。",
  wrongHint:"洗澡缺不了什麼？" },

{ id:"U-S3-008", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"他做錯事還一直＿＿解，讓人更生氣。",
  options:["辯","辨","辦","瓣"], answerIndex:0,
  explanation:"「辯」中間是「言」，和用言語爭論有關。「辨」中間是一點一撇（分辨）、「辦」中間是「力」（辦理）。",
  correctFeedback:"中間那個部件，決定了整個字的意思。",
  wrongHint:"這三個字外框一樣，只有中間不同。爭論要用什麼？" },

{ id:"U-S3-009", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"力", difficulty:"挑戰", charOptions:true,
  question:"這件事交給我，我一定＿＿到好。",
  options:["辦","辯","辨","瓣"], answerIndex:0,
  explanation:"「辦」中間是「力」，要出力去做事情。",
  correctFeedback:"做事要出力，「力」就在中間。",
  wrongHint:"「＿事情」需要出力氣，還是需要吵架？" },

{ id:"U-S3-010", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"糸", difficulty:"標準", charOptions:true,
  question:"這條圍巾是純棉的，摸起來很＿＿密。",
  options:["綿","棉","眠","免"], answerIndex:0,
  explanation:"「綿」帶「糸」，指絲棉、連續不斷。「棉」帶「木」，指棉花這種植物。這裡形容質地細密綿長，用「綿」。",
  correctFeedback:"植物用「棉」，質地用「綿」，分得很細。",
  wrongHint:"一個是植物，一個是質地。「＿密」在形容什麼？" },

{ id:"U-S3-011", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"氵", difficulty:"標準", charOptions:true,
  question:"我們搭船＿＿過這條大河。",
  options:["渡","度","鍍","踱"], answerIndex:0,
  explanation:"過河要用水路，用帶「氵」的「渡」。「度」是程度、「鍍」是金屬加工。",
  correctFeedback:"水上通行，帶三點水。",
  wrongHint:"過河的時候，腳下是什麼？" },

{ id:"U-S3-012", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"金", difficulty:"挑戰", charOptions:true,
  question:"這隻獎盃外面＿＿了一層金。",
  options:["鍍","渡","度","踱"], answerIndex:0,
  explanation:"「鍍」帶「金」，指在物體表面覆上一層金屬。",
  correctFeedback:"金屬的工序，帶金字旁。",
  wrongHint:"「＿一層金」是在處理金屬，還是在過河？" },

{ id:"U-S3-013", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"這件事我早就＿＿在筆記本上了。",
  options:["記","紀","己","忌"], answerIndex:0,
  explanation:"「記」帶「言」，和記錄、寫下說過的話有關。「紀」帶「糸」，多用於「世紀」「紀律」。",
  correctFeedback:"寫下來的話，帶「言」。",
  wrongHint:"寫筆記是在記錄語言，還是在整理絲線？" },

{ id:"U-S3-014", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"辶", difficulty:"標準", charOptions:true,
  question:"他不小心把手機＿＿失在公車上了。",
  options:["遺","遣","貴","匱"], answerIndex:0,
  explanation:"「遺」帶「辶」，本來和東西在路上掉落、留下有關。",
  correctFeedback:"東西掉在路上，「辶」就出現了。",
  wrongHint:"東西是在移動的過程中不見的。哪個部件代表移動？" },

{ id:"U-S3-015", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"亻", difficulty:"挑戰", charOptions:true,
  question:"他弄壞了公物，必須負責＿＿還。",
  options:["償","嘗","賞","裳"], answerIndex:0,
  explanation:"「償」左邊是「亻」，指人歸還、抵補；不過它的意思也和財物有關。「嘗」是品嘗、「賞」帶「貝」是賞賜。",
  correctFeedback:"很好，這一組要靠語意再確認一次。",
  wrongHint:"「＿還」是人做的行為。先找有「亻」的字。" },

{ id:"U-S3-016", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"扌", difficulty:"標準", charOptions:true,
  question:"聽到有人叫他，他立刻＿＿起頭來。",
  options:["抬","苔","治","怠"], answerIndex:0,
  explanation:"抬頭是身體的動作，用帶「扌」的「抬」。",
  correctFeedback:"動作找提手旁。",
  wrongHint:"「＿起頭」是一個動作。" },

{ id:"U-S3-017", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"辶", difficulty:"標準", charOptions:true,
  question:"車站有很多人在＿＿接遠道而來的親友。",
  options:["迎","仰","抑","昂"], answerIndex:0,
  explanation:"迎接要走過去，用帶「辶」的「迎」。「仰」帶亻是抬頭、「抑」帶扌是壓下。",
  correctFeedback:"接人要走過去，「辶」在路上。",
  wrongHint:"迎接的時候，你會不會移動位置？" },

{ id:"U-S3-018", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"扌", difficulty:"挑戰", charOptions:true,
  question:"他努力＿＿制住自己的怒氣。",
  options:["抑","仰","迎","昂"], answerIndex:0,
  explanation:"「抑」帶「扌」，本來是用手向下壓，引申為壓制。",
  correctFeedback:"用手往下壓，就是「抑」。",
  wrongHint:"「壓制」是往下壓的動作，需要用什麼？" },

{ id:"U-S3-019", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"貝", difficulty:"標準", charOptions:true,
  question:"這幅畫非常珍＿＿，博物館收藏了很久。",
  options:["貴","跪","櫃","匱"], answerIndex:0,
  explanation:"「貴」帶「貝」，和價值高有關。「櫃」帶木、「跪」帶足。",
  correctFeedback:"價值的線索仍然是「貝」。",
  wrongHint:"珍貴講的是價值。價值和哪個部件有關？" },

{ id:"U-S3-020", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"日", difficulty:"挑戰", charOptions:true,
  question:"夕陽西下，天色已近日＿＿。",
  options:["暮","慕","墓","幕"], answerIndex:0,
  explanation:"「暮」下面是「日」，指太陽下山、天快黑。「慕」下面是心、「墓」下面是土、「幕」下面是巾。",
  correctFeedback:"下半部一換，意思全變，你抓得很準。",
  wrongHint:"這四個字上半部一樣。天色和什麼有關？" },

{ id:"U-S3-021", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"心", difficulty:"挑戰", charOptions:true,
  question:"他從小就很仰＿＿這位科學家。",
  options:["慕","暮","墓","幕"], answerIndex:0,
  explanation:"「慕」下面是「心」，和內心的敬愛、嚮往有關。",
  correctFeedback:"敬愛發生在心裡。",
  wrongHint:"仰慕是一種感覺。哪個字底下是心？" },

{ id:"U-S3-022", level:"upper", stage:3, mode:["adventure","quick","challenge"], skillType:"應用", radical:"金", difficulty:"挑戰", charOptions:true,
  question:"這把劍是用好鋼＿＿造出來的。",
  options:["鍛","緞","段","煅"], answerIndex:0,
  explanation:"「鍛」帶「金」，指反覆敲打金屬。「緞」帶「糸」，是絲織品。這裡在講鋼，所以用「鍛」。",
  correctFeedback:"鋼是金屬，當然找金字旁。",
  wrongHint:"「鋼」是金屬還是布？造劍要用哪一種？" }
);

/* ========================================================
   高年級 · 第 4 關 陌生字推理（22 題）全為推理
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-S4-001", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"氵", difficulty:"標準", focus:"湍",
  question:"「湍」這個字最可能和什麼有關？",
  options:["水流","火焰","布料","石頭"], answerIndex:0,
  explanation:"「湍」左邊是「氵」，先往水的方向推。它指急速的水流，例如「湍急」。",
  correctFeedback:"就算不會念，方向已經對了。",
  wrongHint:"先看左邊的部件，不要急著猜讀音。" },

{ id:"U-S4-002", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"貝", difficulty:"標準", focus:"賒",
  question:"「賒」這個字最可能和什麼有關？",
  options:["金錢或買賣","走路","天氣","飲食"], answerIndex:0,
  explanation:"「賒」左邊是「貝」，多半和錢財有關。「賒帳」是先取貨、日後付款。",
  correctFeedback:"「貝」是錢的招牌。",
  wrongHint:"左邊的部件和「賠」「賺」是同一個。" },

{ id:"U-S4-003", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"辶", difficulty:"標準", focus:"邂",
  question:"「邂」這個字最可能和什麼有關？",
  options:["行走或相遇","飲食","器皿","疾病"], answerIndex:0,
  explanation:"「邂」帶「辶」，和行走、路上發生的事有關。「邂逅」是在路上意外相遇。",
  correctFeedback:"路上的相遇，「辶」先透露了。",
  wrongHint:"這個字左下方那個部件像一條路。" },

{ id:"U-S4-004", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"灬", difficulty:"挑戰", focus:"煦",
  question:"「煦」這個字最可能和什麼有關？",
  options:["溫暖或熱","寒冷","潮溼","堅硬"], answerIndex:0,
  explanation:"「煦」下面是「灬」（火），多半和溫熱有關。「和煦」形容陽光溫暖。",
  correctFeedback:"四點火在底下，字就暖起來了。",
  wrongHint:"下面那四點不是水滴，是另一種東西。" },

{ id:"U-S4-005", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"忄", difficulty:"標準", focus:"憫",
  question:"「憫」這個字最可能和什麼有關？",
  options:["心裡的感受","金屬工具","農作物","車輛"], answerIndex:0,
  explanation:"「憫」左邊是「忄」，多半和心情有關。「憐憫」是對別人的不幸感到不忍。",
  correctFeedback:"豎心旁一出現，就往感覺想。",
  wrongHint:"左邊的部件是「心」的變形。" },

{ id:"U-S4-006", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"言", difficulty:"標準", focus:"諭",
  question:"「諭」這個字最可能和什麼有關？",
  options:["用言語告訴或吩咐","用手搬運","用腳行走","用眼觀察"], answerIndex:0,
  explanation:"「諭」左邊是「言」，和說話、告知有關。「曉諭」是明白地告訴別人。",
  correctFeedback:"「言」出現，就有人在說話。",
  wrongHint:"左邊的部件和「說」「話」「請」是同一家。" },

{ id:"U-S4-007", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"金", difficulty:"標準", focus:"鎔",
  question:"「鎔」這個字最可能和什麼有關？",
  options:["金屬","布料","穀物","鳥類"], answerIndex:0,
  explanation:"「鎔」左邊是「金」，和金屬的熔化、鑄造有關。",
  correctFeedback:"金字旁不會騙人。",
  wrongHint:"左邊的部件，和「錢」「銀」共用。" },

{ id:"U-S4-008", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"頁", difficulty:"挑戰", focus:"顱",
  question:"「顱」這個字最可能和什麼有關？",
  options:["頭部","書頁","腳掌","樹葉"], answerIndex:0,
  explanation:"「顱」右邊是「頁」，「頁」本義是頭。「頭顱」就是人的頭。",
  correctFeedback:"「頁」的本義是頭，不是紙。",
  wrongHint:"別被「一頁紙」誤導了。這個部件本來畫的是身體的一部分。" },

{ id:"U-S4-009", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"魚", difficulty:"標準", focus:"鰭",
  question:"「鰭」這個字最可能和什麼有關？",
  options:["魚身上的構造","鳥的羽毛","樹的枝葉","車的零件"], answerIndex:0,
  explanation:"「鰭」左邊是「魚」，多半和魚有關。它指魚用來游動、保持平衡的部位。",
  correctFeedback:"魚字旁一出現，就往水裡想。",
  wrongHint:"左邊的部件和「鯨」「鱗」是同一個。" },

{ id:"U-S4-010", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"疒", difficulty:"標準", focus:"疹",
  question:"「疹」這個字最可能和什麼有關？",
  options:["疾病或皮膚的病症","房屋","刀劍","農具"], answerIndex:0,
  explanation:"「疹」外框是「疒」，多半和疾病有關。",
  correctFeedback:"病字頭一出現，就想到身體不適。",
  wrongHint:"外框那個部件，和「病」「痛」是同一個。" },

{ id:"U-S4-011", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"鬼", difficulty:"挑戰", focus:"魅",
  question:"「魅」這個字最可能和什麼有關？",
  options:["神鬼或看不見的力量","金屬工具","水中生物","農作物"], answerIndex:0,
  explanation:"「魅」左邊是「鬼」，古人用來指精怪一類看不見的存在。「魅力」是後來引申的用法。",
  correctFeedback:"抽象的字，也有部件線索。",
  wrongHint:"左邊那個部件，和「魂」「魄」是同一家。" },

{ id:"U-S4-012", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"見", difficulty:"挑戰", focus:"覷",
  question:"「覷」這個字最可能和什麼有關？",
  options:["看","聽","嗅","嘗"], answerIndex:0,
  explanation:"「覷」右邊是「見」，和看有關。「面面相覷」就是彼此對看。",
  correctFeedback:"「見」裡有一隻眼睛。",
  wrongHint:"右邊那個部件，和「視」「觀」共用。" },

{ id:"U-S4-013", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"禾", difficulty:"標準", focus:"稼",
  question:"「稼」這個字最可能和什麼有關？",
  options:["農作或種田","家具","房屋買賣","車輛"], answerIndex:0,
  explanation:"「稼」左邊是「禾」，多半和穀物、耕種有關。「耕稼」就是種田。",
  correctFeedback:"你沒被右邊的「家」帶走。",
  wrongHint:"這個字有「禾」也有「家」。哪一邊比較常提示意思？" },

{ id:"U-S4-014", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"皿", difficulty:"挑戰", focus:"盥",
  question:"「盥」這個字最可能和什麼有關？",
  options:["用水在器皿中洗手","切割東西","走路","說話"], answerIndex:0,
  explanation:"「盥」下面是「皿」（器皿），中間有「水」。整個字畫的是雙手在盆中洗手，所以「盥洗室」是洗手的地方。",
  correctFeedback:"把整個字拆開看，畫面就出來了。",
  wrongHint:"這個字下面是一個容器，中間有水。有人在做什麼？" },

{ id:"U-S4-015", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"弓", difficulty:"標準", focus:"弩",
  question:"「弩」這個字最可能和什麼有關？",
  options:["弓箭一類的武器","繩索","器皿","布料"], answerIndex:0,
  explanation:"「弩」下面是「弓」，多半和弓箭有關。弩是一種用機械發射箭的弓。",
  correctFeedback:"下面那把弓，就是答案。",
  wrongHint:"這個字下半部是一種武器。" },

{ id:"U-S4-016", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"阝", difficulty:"挑戰", focus:"隘",
  question:"「隘」的「阝」在左邊，這個字最可能和什麼有關？",
  options:["地勢，例如狹窄的山口","城市名稱","耳朵","刀劍"], answerIndex:0,
  explanation:"左邊的「阝」由「阜」（土山）變來，所以「隘」多半和地形有關。「關隘」是狹窄難行的山口。",
  correctFeedback:"左阝是山，你記住了。",
  wrongHint:"回想一下：「阝」在左邊和在右邊，代表的東西不一樣。" },

{ id:"U-S4-017", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"阝", difficulty:"挑戰", focus:"鄙",
  question:"「鄙」的「阝」在右邊，這個字最可能和什麼有關？",
  options:["地方，例如邊遠的城鎮","山的高度","水的深淺","火的溫度"], answerIndex:0,
  explanation:"右邊的「阝」由「邑」變來，和城邑、地方有關。「鄙」原指邊遠的地方，後來才引申出輕視的意思。",
  correctFeedback:"右阝是城，兩個「阝」你都分清楚了。",
  wrongHint:"這個「阝」站在字的右邊，不是左邊。" },

{ id:"U-S4-018", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"彳", difficulty:"標準", focus:"徜",
  question:"「徜」這個字最可能和什麼有關？",
  options:["行走或漫步","飲食","器皿","疾病"], answerIndex:0,
  explanation:"「徜」左邊是「彳」，和走路有關。「徜徉」是自在地來回走動。",
  correctFeedback:"「彳」是一條路，人在上面走。",
  wrongHint:"左邊那個部件，和「往」「徒」共用。" },

{ id:"U-S4-019", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"糸", difficulty:"標準", focus:"縈",
  question:"「縈」這個字最可能和什麼有關？",
  options:["絲線纏繞","火的燃燒","土的堆積","石頭的撞擊"], answerIndex:0,
  explanation:"「縈」下面是「糸」，和絲線有關。「縈繞」是像線一樣纏繞不去。",
  correctFeedback:"線一纏上，就繞不開了。",
  wrongHint:"這個字的下半部，和「線」「織」共用。" },

{ id:"U-S4-020", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"刂", difficulty:"標準", focus:"剔",
  question:"「剔」這個字最可能和什麼有關？",
  options:["用刀挑除","用手抱","用眼看","用耳聽"], answerIndex:0,
  explanation:"「剔」右邊是「刂」，多半和刀的動作有關。「剔除」就是把不要的挑掉。",
  correctFeedback:"立刀旁站在右邊，動作很鋒利。",
  wrongHint:"右邊那兩豎，是一把直立的刀。" },

{ id:"U-S4-021", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"隹", difficulty:"挑戰", focus:"隼",
  question:"「隼」這個字最可能和什麼有關？",
  options:["鳥","魚","樹","石"], answerIndex:0,
  explanation:"「隼」上半部是「隹」，本義是短尾的鳥。隼是一種飛得很快的猛禽。",
  correctFeedback:"「隹」在上面，一隻鳥停在那裡。",
  wrongHint:"上半部那個部件，和「雀」「雁」共用。" },

{ id:"U-S4-022", level:"upper", stage:4, mode:["adventure","quick","challenge"], skillType:"推理", radical:"攵", difficulty:"挑戰", focus:"斂",
  question:"「斂」這個字最可能和什麼有關？",
  options:["某種收攏、施行的動作","天氣","食物","布料花色"], answerIndex:0,
  explanation:"「斂」右邊是「攵」，這個部件常表示有人動手施加某種動作。「收斂」就是把散開的收攏起來。",
  correctFeedback:"「攵」代表有人在動手。",
  wrongHint:"右邊那個部件，和「教」「改」「救」共用。" }
);

/* ========================================================
   高年級 · 第 5 關 終極密碼（16 題）四種能力混合
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-S5-001", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"辨認", radical:"阝", difficulty:"挑戰", charOptions:true,
  question:"下列哪一個字的「阝」在左邊，因此和山丘、地勢有關？",
  options:["陡","郊","都","郡"], answerIndex:0,
  explanation:"「陡」的「阝」在左邊，由「阜」變來，和地勢陡峭有關。其餘三字的「阝」在右邊，和城邑有關。",
  correctFeedback:"位置決定意思，這是高年級的關鍵。",
  wrongHint:"先看「阝」站在字的哪一邊。" },

{ id:"U-S5-002", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"灬", difficulty:"標準", charOptions:true,
  question:"這鍋湯已經＿＿滾了，可以關火了。",
  options:["煮","著","者","諸"], answerIndex:0,
  explanation:"「煮」下面是「灬」（火），和加熱有關。",
  correctFeedback:"四點火在底下燒。",
  wrongHint:"煮湯需要火。哪一個字下面有四點？" },

{ id:"U-S5-003", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"皿", difficulty:"挑戰", focus:"盅",
  question:"「盅」這個字最可能和什麼有關？",
  options:["杯碗一類的容器","忠心","蟲子","中間"], answerIndex:0,
  explanation:"「盅」下面是「皿」，多半和器皿有關。它指沒有把手的小杯子。",
  correctFeedback:"上面表聲音，下面表意思，你分對了。",
  wrongHint:"這個字上面是「中」，下面是另一個部件。哪一個負責提示意思？" },

{ id:"U-S5-004", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"欠", difficulty:"標準",
  question:"「歌、吹、歎」這幾個字裡的「欠」，最可能和什麼有關？",
  options:["張口呼氣或發聲","缺少東西","走路","金錢"], answerIndex:0,
  explanation:"「欠」本來畫的是人張口呼氣的樣子，所以常和發聲、呼吸有關。「欠錢」的用法是後來才有的。",
  correctFeedback:"「欠」的本義是張口，不是缺少。",
  wrongHint:"唱歌、吹氣、歎息，都要張開什麼？" },

{ id:"U-S5-005", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"糸", difficulty:"挑戰", charOptions:true,
  question:"這件事情前因後果很複雜，要慢慢＿＿理。",
  options:["梳","疏","蔬","輸"], answerIndex:0,
  explanation:"「梳理」原指用梳子把頭髮理順，引申為把事情理清楚。「梳」帶「木」，因為古代梳子多用木頭做。",
  correctFeedback:"梳子是木頭做的，所以帶「木」。",
  wrongHint:"梳子這樣東西，用什麼材料做？" },

{ id:"U-S5-006", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"疒", difficulty:"標準", focus:"癒",
  question:"「癒」這個字最可能和什麼有關？",
  options:["疾病，或病好了","房屋","車輛","布料"], answerIndex:0,
  explanation:"「癒」外框是「疒」，和疾病有關。「痊癒」是病好了。",
  correctFeedback:"病字頭出現，就往身體狀況想。",
  wrongHint:"外框那個部件像一張床。" },

{ id:"U-S5-007", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"辨認", radical:"灬", difficulty:"挑戰", charOptions:true,
  question:"下列哪一個字的「灬」是由「火」變來，和熱有關？",
  options:["熱","魚","馬","鳥"], answerIndex:0,
  explanation:"「熱」的「灬」由「火」變來。「魚」「馬」「鳥」下面的「灬」則是尾巴或腳的變形，不表示火。",
  correctFeedback:"很厲害！「灬」不一定都是火，你抓到例外了。",
  wrongHint:"魚和馬的下半部，比較可能是火，還是牠們身體的一部分？" },

{ id:"U-S5-008", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"老師＿＿勵我們多讀課外書。",
  options:["鼓","股","故","估"], answerIndex:0,
  explanation:"「鼓勵」的「鼓」原指敲鼓，引申為激發。若不確定，可先排除帶「亻」的「估」和帶「肉月」的「股」。",
  correctFeedback:"用排除法縮小範圍，很好的策略。",
  wrongHint:"先把明顯和「人」「身體」有關的字刪掉。" },

{ id:"U-S5-009", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"穴", difficulty:"標準",
  question:"「空、窗、穿」這幾個字，大多和什麼意思有關？",
  options:["洞穴、空間或通過","火焰","布料","金屬"], answerIndex:0,
  explanation:"這三個字上面都是「穴」，本義是洞穴，常和空間、孔洞有關。",
  correctFeedback:"洞穴在字的頭上。",
  wrongHint:"窗戶是牆上的什麼？穿過去要經過什麼？" },

{ id:"U-S5-010", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"彳", difficulty:"標準", focus:"徘",
  question:"「徘」這個字最可能和什麼有關？",
  options:["來回走動","排列整齊","悲傷","飲食"], answerIndex:0,
  explanation:"「徘」左邊是「彳」，和走路有關。「徘徊」是在原地來回走。",
  correctFeedback:"你沒被右邊的「非」帶走。",
  wrongHint:"左邊那三筆，是道路的意思。" },

{ id:"U-S5-011", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"扌", difficulty:"挑戰", charOptions:true,
  question:"他小心地＿＿開擋在門前的紙箱。",
  options:["挪","那","娜","哪"], answerIndex:0,
  explanation:"移動東西是手的動作，用帶「扌」的「挪」。",
  correctFeedback:"動作的字，多半帶提手旁。",
  wrongHint:"這四個字讀音接近。搬開箱子要用什麼？" },

{ id:"U-S5-012", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"礻", difficulty:"挑戰",
  question:"「祈、祝、神」這幾個字裡的「礻」，最可能和什麼有關？",
  options:["祭祀或神明","衣服布料","石頭","禾苗"], answerIndex:0,
  explanation:"「礻」由「示」變來，和祭祀、神明有關。要注意它和「衤」（衣）長得很像，「衤」多一點。",
  correctFeedback:"「礻」和「衤」只差一點，你分出來了。",
  wrongHint:"「祈禱」「祝福」和什麼有關？神明還是衣服？" },

{ id:"U-S5-013", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"辨認", radical:"衤", difficulty:"挑戰", charOptions:true,
  question:"下列哪一個字含有「衤」（衣）部件？",
  options:["裙","祝","神","社"], answerIndex:0,
  explanation:"「裙」左邊是「衤」，和衣服有關。其餘三字左邊是「礻」，和祭祀有關。「衤」比「礻」多一點。",
  correctFeedback:"多一點就是衣服，少一點就是神明。",
  wrongHint:"仔細數一數左邊的筆畫，哪一個多一點？" },

{ id:"U-S5-014", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"推理", radical:"貝", difficulty:"標準", focus:"贖",
  question:"「贖」這個字最可能和什麼有關？",
  options:["用錢財換回東西","讀書","走路","說話"], answerIndex:0,
  explanation:"「贖」左邊是「貝」，和金錢有關。「贖回」是付出代價把東西換回來。",
  correctFeedback:"你沒被右邊的「賣」影響判斷。",
  wrongHint:"左邊那個部件，古代拿來當錢用。" },

{ id:"U-S5-015", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"應用", radical:"頁", difficulty:"標準", charOptions:true,
  question:"他低著頭，臉上沒有一點笑容，很憔＿＿。",
  options:["悴","粹","碎","脆"], answerIndex:0,
  explanation:"「悴」左邊是「忄」，和心情、精神有關。「憔悴」形容人精神不好、面容消瘦。",
  correctFeedback:"精神狀態的字，帶豎心旁。",
  wrongHint:"憔悴形容的是心情和精神，不是石頭也不是米。" },

{ id:"U-S5-016", level:"upper", stage:5, mode:["adventure","challenge"], skillType:"分類", radical:"艮", difficulty:"挑戰",
  question:"「跟、根、限」這三個字都有「艮」。關於「艮」的作用，下列說法哪一個最恰當？",
  options:["在這三個字裡主要提示讀音，意思要看另一個部件","一定表示停止","一定表示眼睛","一定表示土地"], answerIndex:0,
  explanation:"「跟」的意思看「足」、「根」看「木」、「限」看左「阝」。「艮」在這裡主要負責聲音。並不是每個部件都提示意思。",
  correctFeedback:"這是最重要的一課：部件有的表意、有的表音。",
  wrongHint:"這三個字意思差很多，但讀音都很接近。共用的部件負責什麼？" }
);

/* ========================================================
   高年級 · 後測（20 題）語氣中性、不加故事包裝
   ======================================================== */
QUESTION_BANK.push(
{ id:"U-PT-001", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"刂", difficulty:"基礎",
  question:"「刂」這個部件，最常和哪一類意思有關？",
  options:["刀或切割","水或液體","說話","房屋"], answerIndex:0,
  explanation:"「刂」是「刀」的變形，常和切割、分開有關。",
  correctFeedback:"正確。",
  wrongHint:"請回想「割」「剪」「刻」的共同部件。" },

{ id:"U-PT-002", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"頁", difficulty:"標準",
  question:"「頁」這個部件的本義最接近下列何者？",
  options:["人的頭部","一張紙","樹葉","腳掌"], answerIndex:0,
  explanation:"「頁」本來畫的是人的頭，所以「頭」「顏」「頸」都用它。",
  correctFeedback:"正確。",
  wrongHint:"「一頁紙」是後來才有的用法。" },

{ id:"U-PT-003", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"灬", difficulty:"標準",
  question:"「煮、熱、蒸」下面的「灬」代表什麼？",
  options:["火","水","土","風"], answerIndex:0,
  explanation:"「灬」是「火」放在字底部的寫法。",
  correctFeedback:"正確。",
  wrongHint:"這三個字都需要加熱。" },

{ id:"U-PT-004", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"阝", difficulty:"挑戰",
  question:"「阝」放在字的左邊時，最常和什麼有關？",
  options:["山丘或地勢高低","城市或地方","耳朵","刀劍"], answerIndex:0,
  explanation:"左邊的「阝」由「阜」（土山）變來，如「陸」「陡」「陵」。",
  correctFeedback:"正確。",
  wrongHint:"請比較「陡」和「郊」的「阝」位置。" },

{ id:"U-PT-005", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"阝", difficulty:"挑戰",
  question:"「阝」放在字的右邊時，最常和什麼有關？",
  options:["城市、地方或行政區","山丘地勢","耳朵","車輛"], answerIndex:0,
  explanation:"右邊的「阝」由「邑」變來，如「郊」「都」「郡」。",
  correctFeedback:"正確。",
  wrongHint:"「都市」「郊區」講的是人聚居的地方。" },

{ id:"U-PT-006", level:"upper", stage:"postTest", mode:["postTest"], skillType:"分類", radical:"彳", difficulty:"標準",
  question:"「往、徒、復」的「彳」最常和什麼有關？",
  options:["行走或道路","兩個人","心情","飲食"], answerIndex:0,
  explanation:"「彳」由「行」變來，和道路、行走有關，雖然俗稱「雙人旁」。",
  correctFeedback:"正確。",
  wrongHint:"別被「雙人旁」這個俗稱誤導。" },

{ id:"U-PT-007", level:"upper", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"貝", difficulty:"標準", charOptions:true,
  question:"下列哪一個字含有「貝」部件？",
  options:["賺","嫌","謙","歉"], answerIndex:0,
  explanation:"「賺」左邊是「貝」，和金錢有關。",
  correctFeedback:"正確。",
  wrongHint:"賺錢和什麼有關？" },

{ id:"U-PT-008", level:"upper", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"礻", difficulty:"挑戰", charOptions:true,
  question:"下列哪一個字含有「礻」（示）部件？",
  options:["祝","裙","被","補"], answerIndex:0,
  explanation:"「祝」左邊是「礻」，和祭祀、神明有關。其餘三字左邊是「衤」（衣）。",
  correctFeedback:"正確。",
  wrongHint:"「礻」比「衤」少一點。" },

{ id:"U-PT-009", level:"upper", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"皿", difficulty:"標準", charOptions:true,
  question:"下列哪一個字含有「皿」部件？",
  options:["盛","盯","眉","看"], answerIndex:0,
  explanation:"「盛」下面是「皿」，和容器有關。其餘三字含「目」。",
  correctFeedback:"正確。",
  wrongHint:"「皿」和「目」外形接近，請注意下半部。" },

{ id:"U-PT-010", level:"upper", stage:"postTest", mode:["postTest"], skillType:"辨認", radical:"疒", difficulty:"標準", charOptions:true,
  question:"下列哪一個字含有「疒」部件？",
  options:["疫","役","投","股"], answerIndex:0,
  explanation:"「疫」外框是「疒」，和疾病有關。",
  correctFeedback:"正確。",
  wrongHint:"「瘟疫」和身體狀況有關。" },

{ id:"U-PT-011", level:"upper", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"貝", difficulty:"標準", charOptions:true,
  question:"選出正確的字：他撞壞了圍籬，必須＿＿償損失。",
  options:["賠","陪","倍","培"], answerIndex:0,
  explanation:"賠償和金錢有關，用帶「貝」的「賠」。",
  correctFeedback:"正確。",
  wrongHint:"賠償要付出什麼？" },

{ id:"U-PT-012", level:"upper", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"火", difficulty:"標準", charOptions:true,
  question:"選出正確的字：這裡氣候乾＿＿，很少下雨。",
  options:["燥","躁","澡","操"], answerIndex:0,
  explanation:"乾燥和熱、缺水有關，用帶「火」的「燥」。",
  correctFeedback:"正確。",
  wrongHint:"「躁」帶足，是性子急。" },

{ id:"U-PT-013", level:"upper", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"氵", difficulty:"標準", charOptions:true,
  question:"選出正確的字：我們搭渡輪＿＿海到對岸。",
  options:["渡","度","鍍","踱"], answerIndex:0,
  explanation:"過海走水路，用帶「氵」的「渡」。",
  correctFeedback:"正確。",
  wrongHint:"過海和水有關。" },

{ id:"U-PT-014", level:"upper", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"日", difficulty:"挑戰", charOptions:true,
  question:"選出正確的字：日＿＿時分，鳥兒紛紛回巢。",
  options:["暮","慕","墓","幕"], answerIndex:0,
  explanation:"「暮」下面是「日」，指太陽下山的時候。",
  correctFeedback:"正確。",
  wrongHint:"時間和太陽有關。" },

{ id:"U-PT-015", level:"upper", stage:"postTest", mode:["postTest"], skillType:"應用", radical:"言", difficulty:"標準", charOptions:true,
  question:"選出正確的字：他在會議上為自己的做法＿＿護。",
  options:["辯","辨","辦","瓣"], answerIndex:0,
  explanation:"辯護要用言語，「辯」中間是「言」。",
  correctFeedback:"正確。",
  wrongHint:"三個字外框相同，請看中間。" },

{ id:"U-PT-016", level:"upper", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"氵", difficulty:"標準", focus:"涸",
  question:"「涸」這個字最可能和什麼有關？",
  options:["水，例如乾枯的水源","火","石頭","布料"], answerIndex:0,
  explanation:"「涸」左邊是「氵」，和水有關。「乾涸」是水乾了。",
  correctFeedback:"正確。",
  wrongHint:"請看左邊的部件。" },

{ id:"U-PT-017", level:"upper", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"禾", difficulty:"標準", focus:"穗",
  question:"「穗」這個字最可能和什麼有關？",
  options:["穀物","金屬","鳥類","器皿"], answerIndex:0,
  explanation:"「穗」左邊是「禾」，和穀類有關。稻穗就是稻子結的果實部分。",
  correctFeedback:"正確。",
  wrongHint:"左邊那個部件長在田裡。" },

{ id:"U-PT-018", level:"upper", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"隹", difficulty:"挑戰", focus:"雛",
  question:"「雛」這個字最可能和什麼有關？",
  options:["幼小的鳥","魚類","車輛","布料"], answerIndex:0,
  explanation:"「雛」右邊是「隹」，本義是短尾的鳥。「雛鳥」就是剛出生的小鳥。",
  correctFeedback:"正確。",
  wrongHint:"右邊那個部件會飛。" },

{ id:"U-PT-019", level:"upper", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"糸", difficulty:"標準", focus:"繚",
  question:"「繚」這個字最可能和什麼有關？",
  options:["絲線或纏繞","火焰","泥土","石頭"], answerIndex:0,
  explanation:"「繚」左邊是「糸」，和絲線、纏繞有關。「繚繞」形容煙霧像線一樣盤旋。",
  correctFeedback:"正確。",
  wrongHint:"左邊那個部件是一束絲。" },

{ id:"U-PT-020", level:"upper", stage:"postTest", mode:["postTest"], skillType:"推理", radical:"艮", difficulty:"挑戰",
  question:"「跟、根、限」都有「艮」，但意思差很多。這說明了什麼？",
  options:["部件有的提示意思，有的只提示讀音","部件永遠提示意思","部件永遠提示讀音","部件沒有作用"], answerIndex:0,
  explanation:"「艮」在這三個字裡主要負責讀音，意思要看「足」「木」「阝」。判斷時要兩邊都看。",
  correctFeedback:"正確。",
  wrongHint:"這三個字讀音接近，但意思無關。共用的部件在做什麼？" }
);

/* ---------------------------------------------------------
   把題庫掛到 window，讓 script.js 取用。
   （若要在 Node 環境測試，也可用 module.exports。）
   --------------------------------------------------------- */
if (typeof window !== "undefined") window.QUESTION_BANK = QUESTION_BANK;
if (typeof module !== "undefined" && module.exports) module.exports = QUESTION_BANK;
